// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package character

import (
	"context"
)

const delete = `-- name: Delete :exec
DELETE FROM characters WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const list = `-- name: List :many
SELECT c.id, c.name, c.corporation_id, c.alliance_id, c.status, c.status_error,
    COALESCE(t.scopes, '') AS scopes, t.expires_at AS token_expires_at, t.issued_at AS token_issued_at
FROM characters c
LEFT JOIN tokens t ON t.character_id = c.id
ORDER BY c.name
`

type ListRow struct {
	ID             int64   `json:"id"`
	Name           string  `json:"name"`
	CorporationID  int64   `json:"corporationId"`
	AllianceID     *int64  `json:"allianceId"`
	Status         string  `json:"status"`
	StatusError    *string `json:"statusError"`
	Scopes         string  `json:"scopes"`
	TokenExpiresAt *int64  `json:"tokenExpiresAt"`
	TokenIssuedAt  *int64  `json:"tokenIssuedAt"`
}

func (q *Queries) List(ctx context.Context) ([]ListRow, error) {
	rows, err := q.db.QueryContext(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRow
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CorporationID,
			&i.AllianceID,
			&i.Status,
			&i.StatusError,
			&i.Scopes,
			&i.TokenExpiresAt,
			&i.TokenIssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStatus = `-- name: SetStatus :exec
UPDATE characters SET status = ?, status_error = ?, updated_at = ? WHERE id = ?
`

type SetStatusParams struct {
	Status      string  `json:"status"`
	StatusError *string `json:"statusError"`
	UpdatedAt   int64   `json:"updatedAt"`
	ID          int64   `json:"id"`
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.ExecContext(ctx, setStatus,
		arg.Status,
		arg.StatusError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsert = `-- name: Upsert :exec
INSERT INTO characters (id, name, owner_hash, corporation_id, alliance_id, status, status_error, added_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'ok', NULL, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    owner_hash = excluded.owner_hash,
    corporation_id = excluded.corporation_id,
    alliance_id = excluded.alliance_id,
    status = 'ok',
    status_error = NULL,
    updated_at = excluded.updated_at
`

type UpsertParams struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	OwnerHash     string `json:"ownerHash"`
	CorporationID int64  `json:"corporationId"`
	AllianceID    *int64 `json:"allianceId"`
	AddedAt       int64  `json:"addedAt"`
	UpdatedAt     int64  `json:"updatedAt"`
}

func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) error {
	_, err := q.db.ExecContext(ctx, upsert,
		arg.ID,
		arg.Name,
		arg.OwnerHash,
		arg.CorporationID,
		arg.AllianceID,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	return err
}
