// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FeatureInfo is what the frontend needs to show opt-in choices.
 */
export class FeatureInfo {
    "name": string;
    "scopes": string[];

    /** Creates a new FeatureInfo instance. */
    constructor($$source: Partial<FeatureInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("scopes" in $$source)) {
            this["scopes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureInfo {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField1_0($$parsedSource["scopes"]);
        }
        return new FeatureInfo($$parsedSource as Partial<FeatureInfo>);
    }
}

export class ListRow {
    "id": number;
    "name": string;
    "corporationId": number;
    "allianceId": number | null;
    "status": string;
    "statusError": string | null;
    "scopes": string;
    "tokenExpiresAt": number | null;
    "tokenIssuedAt": number | null;

    /** Creates a new ListRow instance. */
    constructor($$source: Partial<ListRow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("corporationId" in $$source)) {
            this["corporationId"] = 0;
        }
        if (!("allianceId" in $$source)) {
            this["allianceId"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("statusError" in $$source)) {
            this["statusError"] = null;
        }
        if (!("scopes" in $$source)) {
            this["scopes"] = "";
        }
        if (!("tokenExpiresAt" in $$source)) {
            this["tokenExpiresAt"] = null;
        }
        if (!("tokenIssuedAt" in $$source)) {
            this["tokenIssuedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ListRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListRow($$parsedSource as Partial<ListRow>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
