// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SyncJob is one row of the sync_jobs table. sqlc will generate this.
 */
export class SyncJob {
    "characterId": number;
    "job": string;
    "nextRun": number | null;
    "lastRun": number | null;
    "lastError": string | null;
    "state": string;

    /** Creates a new SyncJob instance. */
    constructor($$source: Partial<SyncJob> = {}) {
        if (!("characterId" in $$source)) {
            this["characterId"] = 0;
        }
        if (!("job" in $$source)) {
            this["job"] = "";
        }
        if (!("nextRun" in $$source)) {
            this["nextRun"] = null;
        }
        if (!("lastRun" in $$source)) {
            this["lastRun"] = null;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = null;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncJob instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncJob($$parsedSource as Partial<SyncJob>);
    }
}
