// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing side of the scheduler.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function List(): $CancellablePromise<$models.SyncJob[]> {
    return $Call.ByID(3107267651).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RunNow(characterID: number, job: string): $CancellablePromise<void> {
    return $Call.ByID(641584388, characterID, job);
}

// Private type creation functions
const $$createType0 = $models.SyncJob.createFrom;
const $$createType1 = $Create.Array($$createType0);
