// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sde

import (
	"context"
)

const getMeta = `-- name: GetMeta :one
SELECT build, release_date, schema FROM meta
`

func (q *Queries) GetMeta(ctx context.Context) (Meta, error) {
	row := q.db.QueryRowContext(ctx, getMeta)
	var i Meta
	err := row.Scan(&i.Build, &i.ReleaseDate, &i.Schema)
	return i, err
}
