-- Code generated by core/sde/gen. DO NOT EDIT.
-- The SDE database: one table per export file, child tables for arrays. See docs/SDE.md.

CREATE TABLE meta (
    build        INTEGER   NOT NULL,
    release_date TIMESTAMP NOT NULL,
    schema       TEXT      NOT NULL
);

CREATE TABLE "accounting_entry_types" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "internal_name" TEXT,
    "journal_message_de" TEXT,
    "journal_message_en" TEXT,
    "journal_message_es" TEXT,
    "journal_message_fr" TEXT,
    "journal_message_ja" TEXT,
    "journal_message_ko" TEXT,
    "journal_message_ru" TEXT,
    "journal_message_zh" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "agent_types" (
    "key" INTEGER PRIMARY KEY,
    "name" TEXT
);

CREATE TABLE "agents_in_space" (
    "key" INTEGER PRIMARY KEY,
    "dungeon_id" INTEGER,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "spawn_point_id" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "ancestries" (
    "key" INTEGER PRIMARY KEY,
    "bloodline_id" BLOODLINE_ID,
    "charisma" INTEGER,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon_id" INTEGER,
    "intelligence" INTEGER,
    "memory" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "perception" INTEGER,
    "short_description" TEXT,
    "willpower" INTEGER
);

CREATE TABLE "applied_proximity_effects" (
    "key" INTEGER PRIMARY KEY,
    "delay_seconds" INTEGER,
    "radius" INTEGER
);

CREATE TABLE "applied_proximity_effects_dbuffs" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "archetypes" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "title_de" TEXT,
    "title_en" TEXT,
    "title_es" TEXT,
    "title_fr" TEXT,
    "title_ja" TEXT,
    "title_ko" TEXT,
    "title_ru" TEXT,
    "title_zh" TEXT
);

CREATE TABLE "bloodlines" (
    "key" BLOODLINE_ID PRIMARY KEY,
    "charisma" INTEGER,
    "corporation_id" CORPORATION_ID,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon_id" INTEGER,
    "intelligence" INTEGER,
    "memory" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "perception" INTEGER,
    "race_id" RACE_ID,
    "willpower" INTEGER
);

CREATE TABLE "blueprints" (
    "key" INTEGER PRIMARY KEY,
    "activities_copying_time" INTEGER,
    "activities_invention_time" INTEGER,
    "activities_manufacturing_time" INTEGER,
    "activities_reaction_time" INTEGER,
    "activities_research_material_time" INTEGER,
    "activities_research_time_time" INTEGER,
    "blueprint_type_id" INTEGER,
    "max_production_limit" INTEGER
);

CREATE TABLE "blueprints_activities_copying_materials" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_copying_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_invention_materials" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_invention_products" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "probability" REAL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_invention_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_manufacturing_materials" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_manufacturing_products" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_manufacturing_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_reaction_materials" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_reaction_products" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_reaction_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_research_material_materials" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_research_material_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_research_time_materials" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "quantity" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "blueprints_activities_research_time_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "categories" (
    "key" INTEGER PRIMARY KEY,
    "icon_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "published" BOOLEAN
);

CREATE TABLE "certificates" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "group_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "certificates_recommended_for" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "certificates_skill_types" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "advanced" INTEGER,
    "basic" INTEGER,
    "elite" INTEGER,
    "improved" INTEGER,
    "standard" INTEGER
);

CREATE TABLE "character_attributes" (
    "key" INTEGER PRIMARY KEY,
    "description" TEXT,
    "icon_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "notes" TEXT,
    "short_description" TEXT
);

CREATE TABLE "character_titles" (
    "key" TEXT PRIMARY KEY,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "clone_grades" (
    "key" INTEGER PRIMARY KEY,
    "name" TEXT
);

CREATE TABLE "clone_grades_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "compressible_types" (
    "key" INTEGER PRIMARY KEY,
    "compressed_type_id" INTEGER
);

CREATE TABLE "contraband_types" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "contraband_types_factions" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "attack_min_sec" REAL,
    "confiscate_min_sec" REAL,
    "fine_by_value" REAL,
    "standing_loss" REAL
);

CREATE TABLE "control_tower_resources" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "control_tower_resources_resources" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "faction_id" FACTION_ID,
    "min_security_level" REAL,
    "purpose" INTEGER,
    "quantity" INTEGER,
    "resource_type_id" INTEGER
);

CREATE TABLE "corporation_activities" (
    "key" INTEGER PRIMARY KEY,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "corporation_role_groups" (
    "key" INTEGER PRIMARY KEY,
    "applies_to" TEXT,
    "applies_to_grantable" TEXT,
    "is_divisional" BOOLEAN,
    "is_locational" BOOLEAN,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "corporation_roles" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "short_name" TEXT
);

CREATE TABLE "corporation_roles_role_group_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "dbuff_collections" (
    "key" INTEGER PRIMARY KEY,
    "aggregate_mode" TEXT,
    "developer_description" TEXT,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "operation_name" TEXT,
    "show_output_value_in_ui" TEXT
);

CREATE TABLE "dbuff_collections_item_modifiers" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "dbuff_collections_location_group_modifiers" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER,
    "group_id" INTEGER
);

CREATE TABLE "dbuff_collections_location_modifiers" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "dbuff_collections_location_required_skill_modifiers" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER,
    "skill_id" INTEGER
);

CREATE TABLE "dogma_attribute_categories" (
    "key" INTEGER PRIMARY KEY,
    "description" TEXT,
    "name" TEXT
);

CREATE TABLE "dogma_attributes" (
    "key" INTEGER PRIMARY KEY,
    "attribute_category_id" INTEGER,
    "charge_recharge_time_id" INTEGER,
    "data_type" INTEGER,
    "default_value" REAL,
    "description" TEXT,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "display_when_zero" BOOLEAN,
    "high_is_good" BOOLEAN,
    "icon_id" INTEGER,
    "max_attribute_id" INTEGER,
    "min_attribute_id" INTEGER,
    "name" TEXT,
    "published" BOOLEAN,
    "stackable" BOOLEAN,
    "tooltip_description_de" TEXT,
    "tooltip_description_en" TEXT,
    "tooltip_description_es" TEXT,
    "tooltip_description_fr" TEXT,
    "tooltip_description_ja" TEXT,
    "tooltip_description_ko" TEXT,
    "tooltip_description_ru" TEXT,
    "tooltip_description_zh" TEXT,
    "tooltip_title_de" TEXT,
    "tooltip_title_en" TEXT,
    "tooltip_title_es" TEXT,
    "tooltip_title_fr" TEXT,
    "tooltip_title_ja" TEXT,
    "tooltip_title_ko" TEXT,
    "tooltip_title_ru" TEXT,
    "tooltip_title_zh" TEXT,
    "unit_id" INTEGER
);

CREATE TABLE "dogma_effects" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "disallow_auto_repeat" BOOLEAN,
    "discharge_attribute_id" INTEGER,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "distribution" INTEGER,
    "duration_attribute_id" INTEGER,
    "effect_category_id" INTEGER,
    "electronic_chance" BOOLEAN,
    "falloff_attribute_id" INTEGER,
    "fitting_usage_chance_attribute_id" INTEGER,
    "guid" TEXT,
    "icon_id" INTEGER,
    "is_assistance" BOOLEAN,
    "is_offensive" BOOLEAN,
    "is_warp_safe" BOOLEAN,
    "name" TEXT,
    "npc_activation_chance_attribute_id" INTEGER,
    "npc_usage_chance_attribute_id" INTEGER,
    "propulsion_chance" BOOLEAN,
    "published" BOOLEAN,
    "range_attribute_id" INTEGER,
    "range_chance" BOOLEAN,
    "resistance_attribute_id" INTEGER,
    "tracking_speed_attribute_id" INTEGER
);

CREATE TABLE "dogma_effects_modifier_info" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "domain" TEXT,
    "effect_id" INTEGER,
    "func" TEXT,
    "group_id" INTEGER,
    "modified_attribute_id" INTEGER,
    "modifying_attribute_id" INTEGER,
    "operation" INTEGER,
    "skill_type_id" INTEGER
);

CREATE TABLE "dogma_units" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "name" TEXT
);

CREATE TABLE "dungeons" (
    "key" INTEGER PRIMARY KEY,
    "archetype_id" INTEGER,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "faction_id" FACTION_ID,
    "gameplay_description_de" TEXT,
    "gameplay_description_en" TEXT,
    "gameplay_description_es" TEXT,
    "gameplay_description_fr" TEXT,
    "gameplay_description_ja" TEXT,
    "gameplay_description_ko" TEXT,
    "gameplay_description_ru" TEXT,
    "gameplay_description_zh" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "dungeons_allowed_ships_list" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "dynamic_item_attributes" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "dynamic_item_attributes_attribute_ids" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "high_is_good" BOOLEAN,
    "max" REAL,
    "min" REAL
);

CREATE TABLE "dynamic_item_attributes_input_output_mapping" (
    "id" INTEGER PRIMARY KEY,
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "resulting_type" INTEGER
);

CREATE TABLE "dynamic_item_attributes_input_output_mapping_applicable_types" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "epic_arcs" (
    "key" INTEGER PRIMARY KEY,
    "arc_restart_interval" INTEGER,
    "faction_id" FACTION_ID,
    "icon_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "epic_arcs_missions" (
    "id" INTEGER PRIMARY KEY,
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "agent_id" INTEGER,
    "fail_mission_id" INTEGER
);

CREATE TABLE "epic_arcs_missions_next_missions" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "expert_systems" (
    "key" INTEGER PRIMARY KEY,
    "duration_days" INTEGER,
    "hidden" BOOLEAN,
    "internal_name" TEXT,
    "retired" BOOLEAN
);

CREATE TABLE "expert_systems_associated_ship_types" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "expert_systems_skills_granted" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "factions" (
    "key" FACTION_ID PRIMARY KEY,
    "corporation_id" CORPORATION_ID,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "flat_logo" TEXT,
    "flat_logo_with_name" TEXT,
    "icon_id" INTEGER,
    "militia_corporation_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "short_description_de" TEXT,
    "short_description_en" TEXT,
    "short_description_es" TEXT,
    "short_description_fr" TEXT,
    "short_description_ja" TEXT,
    "short_description_ko" TEXT,
    "short_description_ru" TEXT,
    "short_description_zh" TEXT,
    "size_factor" REAL,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "unique_name" BOOLEAN
);

CREATE TABLE "factions_member_races" (
    "parent" FACTION_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "fighter_abilities" (
    "key" INTEGER PRIMARY KEY,
    "disallow_in_high_sec" BOOLEAN,
    "disallow_in_low_sec" BOOLEAN,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "icon_id" INTEGER,
    "target_mode" TEXT,
    "tooltip_text_de" TEXT,
    "tooltip_text_en" TEXT,
    "tooltip_text_es" TEXT,
    "tooltip_text_fr" TEXT,
    "tooltip_text_ja" TEXT,
    "tooltip_text_ko" TEXT,
    "tooltip_text_ru" TEXT,
    "tooltip_text_zh" TEXT,
    "turret_graphic_id" INTEGER
);

CREATE TABLE "fighter_abilities_by_type" (
    "key" INTEGER PRIMARY KEY,
    "ability_slot0_ability_id" INTEGER,
    "ability_slot1_ability_id" INTEGER,
    "ability_slot1_cooldown_seconds" INTEGER,
    "ability_slot2_ability_id" INTEGER,
    "ability_slot2_charges_charge_count" INTEGER,
    "ability_slot2_charges_rearm_time_seconds" INTEGER
);

CREATE TABLE "freelance_job_schemas" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "freelance_job_schemas_value" (
    "id" INTEGER PRIMARY KEY,
    "parent" INTEGER NOT NULL,
    "key" TEXT NOT NULL,
    "contribution_multiplier_default_value" INTEGER,
    "contribution_multiplier_description_de" TEXT,
    "contribution_multiplier_description_en" TEXT,
    "contribution_multiplier_description_es" TEXT,
    "contribution_multiplier_description_fr" TEXT,
    "contribution_multiplier_description_ja" TEXT,
    "contribution_multiplier_description_ko" TEXT,
    "contribution_multiplier_description_ru" TEXT,
    "contribution_multiplier_description_zh" TEXT,
    "contribution_multiplier_icon_id" TEXT,
    "contribution_multiplier_max_value" INTEGER,
    "contribution_multiplier_min_value" REAL,
    "contribution_multiplier_title_de" TEXT,
    "contribution_multiplier_title_en" TEXT,
    "contribution_multiplier_title_es" TEXT,
    "contribution_multiplier_title_fr" TEXT,
    "contribution_multiplier_title_ja" TEXT,
    "contribution_multiplier_title_ko" TEXT,
    "contribution_multiplier_title_ru" TEXT,
    "contribution_multiplier_title_zh" TEXT,
    "contribution_multiplier_unset_description_de" TEXT,
    "contribution_multiplier_unset_description_en" TEXT,
    "contribution_multiplier_unset_description_es" TEXT,
    "contribution_multiplier_unset_description_fr" TEXT,
    "contribution_multiplier_unset_description_ja" TEXT,
    "contribution_multiplier_unset_description_ko" TEXT,
    "contribution_multiplier_unset_description_ru" TEXT,
    "contribution_multiplier_unset_description_zh" TEXT,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon_id" TEXT,
    "max_contributions_per_participant_description_de" TEXT,
    "max_contributions_per_participant_description_en" TEXT,
    "max_contributions_per_participant_description_es" TEXT,
    "max_contributions_per_participant_description_fr" TEXT,
    "max_contributions_per_participant_description_ja" TEXT,
    "max_contributions_per_participant_description_ko" TEXT,
    "max_contributions_per_participant_description_ru" TEXT,
    "max_contributions_per_participant_description_zh" TEXT,
    "max_contributions_per_participant_icon_id" TEXT,
    "max_contributions_per_participant_title_de" TEXT,
    "max_contributions_per_participant_title_en" TEXT,
    "max_contributions_per_participant_title_es" TEXT,
    "max_contributions_per_participant_title_fr" TEXT,
    "max_contributions_per_participant_title_ja" TEXT,
    "max_contributions_per_participant_title_ko" TEXT,
    "max_contributions_per_participant_title_ru" TEXT,
    "max_contributions_per_participant_title_zh" TEXT,
    "max_contributions_per_participant_unset_description_de" TEXT,
    "max_contributions_per_participant_unset_description_en" TEXT,
    "max_contributions_per_participant_unset_description_es" TEXT,
    "max_contributions_per_participant_unset_description_fr" TEXT,
    "max_contributions_per_participant_unset_description_ja" TEXT,
    "max_contributions_per_participant_unset_description_ko" TEXT,
    "max_contributions_per_participant_unset_description_ru" TEXT,
    "max_contributions_per_participant_unset_description_zh" TEXT,
    "max_progress_per_contribution_description_de" TEXT,
    "max_progress_per_contribution_description_en" TEXT,
    "max_progress_per_contribution_description_es" TEXT,
    "max_progress_per_contribution_description_fr" TEXT,
    "max_progress_per_contribution_description_ja" TEXT,
    "max_progress_per_contribution_description_ko" TEXT,
    "max_progress_per_contribution_description_ru" TEXT,
    "max_progress_per_contribution_description_zh" TEXT,
    "max_progress_per_contribution_icon_id" TEXT,
    "max_progress_per_contribution_title_de" TEXT,
    "max_progress_per_contribution_title_en" TEXT,
    "max_progress_per_contribution_title_es" TEXT,
    "max_progress_per_contribution_title_fr" TEXT,
    "max_progress_per_contribution_title_ja" TEXT,
    "max_progress_per_contribution_title_ko" TEXT,
    "max_progress_per_contribution_title_ru" TEXT,
    "max_progress_per_contribution_title_zh" TEXT,
    "max_progress_per_contribution_unset_description_de" TEXT,
    "max_progress_per_contribution_unset_description_en" TEXT,
    "max_progress_per_contribution_unset_description_es" TEXT,
    "max_progress_per_contribution_unset_description_fr" TEXT,
    "max_progress_per_contribution_unset_description_ja" TEXT,
    "max_progress_per_contribution_unset_description_ko" TEXT,
    "max_progress_per_contribution_unset_description_ru" TEXT,
    "max_progress_per_contribution_unset_description_zh" TEXT,
    "progress_description_de" TEXT,
    "progress_description_en" TEXT,
    "progress_description_es" TEXT,
    "progress_description_fr" TEXT,
    "progress_description_ja" TEXT,
    "progress_description_ko" TEXT,
    "progress_description_ru" TEXT,
    "progress_description_zh" TEXT,
    "reward_description_de" TEXT,
    "reward_description_en" TEXT,
    "reward_description_es" TEXT,
    "reward_description_fr" TEXT,
    "reward_description_ja" TEXT,
    "reward_description_ko" TEXT,
    "reward_description_ru" TEXT,
    "reward_description_zh" TEXT,
    "target_description_de" TEXT,
    "target_description_en" TEXT,
    "target_description_es" TEXT,
    "target_description_fr" TEXT,
    "target_description_ja" TEXT,
    "target_description_ko" TEXT,
    "target_description_ru" TEXT,
    "target_description_zh" TEXT,
    "title_de" TEXT,
    "title_en" TEXT,
    "title_es" TEXT,
    "title_fr" TEXT,
    "title_ja" TEXT,
    "title_ko" TEXT,
    "title_ru" TEXT,
    "title_zh" TEXT
);

CREATE TABLE "freelance_job_schemas_value_content_tags" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" TEXT
);

CREATE TABLE "freelance_job_schemas_value_parameters" (
    "id" INTEGER PRIMARY KEY,
    "parent" INTEGER NOT NULL,
    "key" TEXT NOT NULL,
    "boolean_choice_label_de" TEXT,
    "boolean_choice_label_en" TEXT,
    "boolean_choice_label_es" TEXT,
    "boolean_choice_label_fr" TEXT,
    "boolean_choice_label_ja" TEXT,
    "boolean_choice_label_ko" TEXT,
    "boolean_choice_label_ru" TEXT,
    "boolean_choice_label_zh" TEXT,
    "boolean_default" BOOLEAN,
    "boolean_description_de" TEXT,
    "boolean_description_en" TEXT,
    "boolean_description_es" TEXT,
    "boolean_description_fr" TEXT,
    "boolean_description_ja" TEXT,
    "boolean_description_ko" TEXT,
    "boolean_description_ru" TEXT,
    "boolean_description_zh" TEXT,
    "boolean_icon_id" TEXT,
    "boolean_option_false_description_de" TEXT,
    "boolean_option_false_description_en" TEXT,
    "boolean_option_false_description_es" TEXT,
    "boolean_option_false_description_fr" TEXT,
    "boolean_option_false_description_ja" TEXT,
    "boolean_option_false_description_ko" TEXT,
    "boolean_option_false_description_ru" TEXT,
    "boolean_option_false_description_zh" TEXT,
    "boolean_option_false_title_de" TEXT,
    "boolean_option_false_title_en" TEXT,
    "boolean_option_false_title_es" TEXT,
    "boolean_option_false_title_fr" TEXT,
    "boolean_option_false_title_ja" TEXT,
    "boolean_option_false_title_ko" TEXT,
    "boolean_option_false_title_ru" TEXT,
    "boolean_option_false_title_zh" TEXT,
    "boolean_option_true_description_de" TEXT,
    "boolean_option_true_description_en" TEXT,
    "boolean_option_true_description_es" TEXT,
    "boolean_option_true_description_fr" TEXT,
    "boolean_option_true_description_ja" TEXT,
    "boolean_option_true_description_ko" TEXT,
    "boolean_option_true_description_ru" TEXT,
    "boolean_option_true_description_zh" TEXT,
    "boolean_option_true_title_de" TEXT,
    "boolean_option_true_title_en" TEXT,
    "boolean_option_true_title_es" TEXT,
    "boolean_option_true_title_fr" TEXT,
    "boolean_option_true_title_ja" TEXT,
    "boolean_option_true_title_ko" TEXT,
    "boolean_option_true_title_ru" TEXT,
    "boolean_option_true_title_zh" TEXT,
    "boolean_title_de" TEXT,
    "boolean_title_en" TEXT,
    "boolean_title_es" TEXT,
    "boolean_title_fr" TEXT,
    "boolean_title_ja" TEXT,
    "boolean_title_ko" TEXT,
    "boolean_title_ru" TEXT,
    "boolean_title_zh" TEXT,
    "item_delivery_delivery_location_description_de" TEXT,
    "item_delivery_delivery_location_description_en" TEXT,
    "item_delivery_delivery_location_description_es" TEXT,
    "item_delivery_delivery_location_description_fr" TEXT,
    "item_delivery_delivery_location_description_ja" TEXT,
    "item_delivery_delivery_location_description_ko" TEXT,
    "item_delivery_delivery_location_description_ru" TEXT,
    "item_delivery_delivery_location_description_zh" TEXT,
    "item_delivery_delivery_location_icon_id" TEXT,
    "item_delivery_delivery_location_max_entries" INTEGER,
    "item_delivery_delivery_location_title_de" TEXT,
    "item_delivery_delivery_location_title_en" TEXT,
    "item_delivery_delivery_location_title_es" TEXT,
    "item_delivery_delivery_location_title_fr" TEXT,
    "item_delivery_delivery_location_title_ja" TEXT,
    "item_delivery_delivery_location_title_ko" TEXT,
    "item_delivery_delivery_location_title_ru" TEXT,
    "item_delivery_delivery_location_title_zh" TEXT,
    "item_delivery_delivery_location_unset_description_de" TEXT,
    "item_delivery_delivery_location_unset_description_en" TEXT,
    "item_delivery_delivery_location_unset_description_es" TEXT,
    "item_delivery_delivery_location_unset_description_fr" TEXT,
    "item_delivery_delivery_location_unset_description_ja" TEXT,
    "item_delivery_delivery_location_unset_description_ko" TEXT,
    "item_delivery_delivery_location_unset_description_ru" TEXT,
    "item_delivery_delivery_location_unset_description_zh" TEXT,
    "item_delivery_description_de" TEXT,
    "item_delivery_description_en" TEXT,
    "item_delivery_description_es" TEXT,
    "item_delivery_description_fr" TEXT,
    "item_delivery_description_ja" TEXT,
    "item_delivery_description_ko" TEXT,
    "item_delivery_description_ru" TEXT,
    "item_delivery_description_zh" TEXT,
    "item_delivery_icon_id" TEXT,
    "item_delivery_inventory_type_description_de" TEXT,
    "item_delivery_inventory_type_description_en" TEXT,
    "item_delivery_inventory_type_description_es" TEXT,
    "item_delivery_inventory_type_description_fr" TEXT,
    "item_delivery_inventory_type_description_ja" TEXT,
    "item_delivery_inventory_type_description_ko" TEXT,
    "item_delivery_inventory_type_description_ru" TEXT,
    "item_delivery_inventory_type_description_zh" TEXT,
    "item_delivery_inventory_type_icon_id" TEXT,
    "item_delivery_inventory_type_title_de" TEXT,
    "item_delivery_inventory_type_title_en" TEXT,
    "item_delivery_inventory_type_title_es" TEXT,
    "item_delivery_inventory_type_title_fr" TEXT,
    "item_delivery_inventory_type_title_ja" TEXT,
    "item_delivery_inventory_type_title_ko" TEXT,
    "item_delivery_inventory_type_title_ru" TEXT,
    "item_delivery_inventory_type_title_zh" TEXT,
    "item_delivery_inventory_type_unset_description_de" TEXT,
    "item_delivery_inventory_type_unset_description_en" TEXT,
    "item_delivery_inventory_type_unset_description_es" TEXT,
    "item_delivery_inventory_type_unset_description_fr" TEXT,
    "item_delivery_inventory_type_unset_description_ja" TEXT,
    "item_delivery_inventory_type_unset_description_ko" TEXT,
    "item_delivery_inventory_type_unset_description_ru" TEXT,
    "item_delivery_inventory_type_unset_description_zh" TEXT,
    "item_delivery_title_de" TEXT,
    "item_delivery_title_en" TEXT,
    "item_delivery_title_es" TEXT,
    "item_delivery_title_fr" TEXT,
    "item_delivery_title_ja" TEXT,
    "item_delivery_title_ko" TEXT,
    "item_delivery_title_ru" TEXT,
    "item_delivery_title_zh" TEXT,
    "matcher_description_de" TEXT,
    "matcher_description_en" TEXT,
    "matcher_description_es" TEXT,
    "matcher_description_fr" TEXT,
    "matcher_description_ja" TEXT,
    "matcher_description_ko" TEXT,
    "matcher_description_ru" TEXT,
    "matcher_description_zh" TEXT,
    "matcher_icon_id" TEXT,
    "matcher_max_entries" INTEGER,
    "matcher_optional" BOOLEAN,
    "matcher_title_de" TEXT,
    "matcher_title_en" TEXT,
    "matcher_title_es" TEXT,
    "matcher_title_fr" TEXT,
    "matcher_title_ja" TEXT,
    "matcher_title_ko" TEXT,
    "matcher_title_ru" TEXT,
    "matcher_title_zh" TEXT,
    "matcher_type" TEXT,
    "matcher_unset_description_de" TEXT,
    "matcher_unset_description_en" TEXT,
    "matcher_unset_description_es" TEXT,
    "matcher_unset_description_fr" TEXT,
    "matcher_unset_description_ja" TEXT,
    "matcher_unset_description_ko" TEXT,
    "matcher_unset_description_ru" TEXT,
    "matcher_unset_description_zh" TEXT
);

CREATE TABLE "freelance_job_schemas_value_parameters_item_delivery_delivery_location_accepted_value_types" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" TEXT
);

CREATE TABLE "freelance_job_schemas_value_parameters_item_delivery_inventory_type_accepted_value_types" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" TEXT
);

CREATE TABLE "freelance_job_schemas_value_parameters_matcher_accepted_value_types" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" TEXT
);

CREATE TABLE "graphic_material_sets" (
    "key" INTEGER PRIMARY KEY,
    "color_hull_a" REAL,
    "color_hull_b" REAL,
    "color_hull_g" REAL,
    "color_hull_r" REAL,
    "color_primary_a" REAL,
    "color_primary_b" REAL,
    "color_primary_g" REAL,
    "color_primary_r" REAL,
    "color_secondary_a" REAL,
    "color_secondary_b" REAL,
    "color_secondary_g" REAL,
    "color_secondary_r" REAL,
    "color_window_a" REAL,
    "color_window_b" REAL,
    "color_window_g" REAL,
    "color_window_r" REAL,
    "custommaterial1" TEXT,
    "custommaterial2" TEXT,
    "description" TEXT,
    "material1" TEXT,
    "material2" TEXT,
    "material3" TEXT,
    "material4" TEXT,
    "res_path_insert" TEXT,
    "sof_faction_name" TEXT,
    "sof_pattern_name" TEXT,
    "sof_race_hint" TEXT
);

CREATE TABLE "graphics" (
    "key" INTEGER PRIMARY KEY,
    "graphic_file" TEXT,
    "icon_folder" TEXT,
    "sof_faction_name" TEXT,
    "sof_hull_name" TEXT,
    "sof_material_set_id" INTEGER,
    "sof_race_name" TEXT
);

CREATE TABLE "graphics_sof_layout" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" TEXT
);

CREATE TABLE "groups" (
    "key" INTEGER PRIMARY KEY,
    "anchorable" BOOLEAN,
    "anchored" BOOLEAN,
    "category_id" INTEGER,
    "fittable_non_singleton" BOOLEAN,
    "icon_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "published" BOOLEAN,
    "use_base_price" BOOLEAN
);

CREATE TABLE "icons" (
    "key" INTEGER PRIMARY KEY,
    "icon_file" TEXT
);

CREATE TABLE "industry_activities" (
    "key" INTEGER PRIMARY KEY,
    "description" TEXT,
    "name" TEXT
);

CREATE TABLE "industry_assembly_lines" (
    "key" INTEGER PRIMARY KEY,
    "activity_id" INTEGER,
    "base_cost_multiplier" REAL,
    "base_material_multiplier" REAL,
    "base_time_multiplier" REAL,
    "description" TEXT,
    "name" TEXT
);

CREATE TABLE "industry_assembly_lines_details_per_category" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "category_id" INTEGER,
    "cost_multiplier" REAL,
    "material_multiplier" REAL,
    "time_multiplier" REAL
);

CREATE TABLE "industry_assembly_lines_details_per_group" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "cost_multiplier" REAL,
    "group_id" INTEGER,
    "material_multiplier" REAL,
    "time_multiplier" REAL
);

CREATE TABLE "industry_assembly_lines_details_per_type_list" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "material_multiplier" REAL,
    "time_multiplier" REAL,
    "type_list_id" INTEGER
);

CREATE TABLE "industry_installation_types" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "industry_installation_types_assembly_lines" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "assembly_line_id" INTEGER
);

CREATE TABLE "industry_modifier_sources" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "industry_modifier_sources_copying_cost" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_copying_time" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_invention_cost" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_invention_time" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_manufacturing_cost" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_manufacturing_material" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER,
    "filter_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_manufacturing_time" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER,
    "filter_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_reaction_material" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER,
    "filter_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_reaction_time" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER,
    "filter_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_research_material_cost" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_research_material_time" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_research_time_cost" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_modifier_sources_research_time_time" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "dogma_attribute_id" INTEGER
);

CREATE TABLE "industry_target_filters" (
    "key" INTEGER PRIMARY KEY,
    "name" TEXT
);

CREATE TABLE "industry_target_filters_category_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "industry_target_filters_group_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "landmarks" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon_id" INTEGER,
    "location_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL
);

CREATE TABLE "link_with_ship" (
    "key" INTEGER PRIMARY KEY,
    "apply_pvp_flag" BOOLEAN,
    "can_relink" BOOLEAN,
    "character_energy_cost" REAL,
    "dbuff_post_link_duration" INTEGER,
    "generate_cyno_inhibitor" BOOLEAN,
    "keep_dbuff_duration_on_link_break" BOOLEAN,
    "link_duration" INTEGER,
    "link_effect_graphic_id_override" INTEGER,
    "linkable_ship_type_list_id" INTEGER,
    "max_link_range" INTEGER,
    "omega_only" BOOLEAN,
    "solarsystem_interference_cost" REAL
);

CREATE TABLE "link_with_ship_dbuffs" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "map_asteroid_belts" (
    "key" INTEGER PRIMARY KEY,
    "celestial_index" INTEGER,
    "orbit_id" INTEGER,
    "orbit_index" INTEGER,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "radius" REAL,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "statistics_density" REAL,
    "statistics_eccentricity" REAL,
    "statistics_escape_velocity" REAL,
    "statistics_locked" BOOLEAN,
    "statistics_mass_dust" REAL,
    "statistics_mass_gas" REAL,
    "statistics_orbit_period" REAL,
    "statistics_orbit_radius" REAL,
    "statistics_rotation_rate" REAL,
    "statistics_spectral_class" TEXT,
    "statistics_surface_gravity" REAL,
    "statistics_temperature" REAL,
    "type_id" TYPE_ID,
    "unique_name_de" TEXT,
    "unique_name_en" TEXT,
    "unique_name_es" TEXT,
    "unique_name_fr" TEXT,
    "unique_name_ja" TEXT,
    "unique_name_ko" TEXT,
    "unique_name_ru" TEXT,
    "unique_name_zh" TEXT
);

CREATE TABLE "map_constellations" (
    "key" INTEGER PRIMARY KEY,
    "faction_id" FACTION_ID,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "region_id" INTEGER,
    "wormhole_class_id" INTEGER
);

CREATE TABLE "map_constellations_solar_system_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_moons" (
    "key" INTEGER PRIMARY KEY,
    "attributes_height_map1" INTEGER,
    "attributes_height_map2" INTEGER,
    "attributes_shader_preset" INTEGER,
    "celestial_index" INTEGER,
    "orbit_id" INTEGER,
    "orbit_index" INTEGER,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "radius" REAL,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "statistics_density" REAL,
    "statistics_eccentricity" REAL,
    "statistics_escape_velocity" REAL,
    "statistics_locked" BOOLEAN,
    "statistics_mass_dust" REAL,
    "statistics_mass_gas" REAL,
    "statistics_orbit_period" REAL,
    "statistics_orbit_radius" REAL,
    "statistics_pressure" REAL,
    "statistics_rotation_rate" REAL,
    "statistics_spectral_class" TEXT,
    "statistics_surface_gravity" REAL,
    "statistics_temperature" REAL,
    "type_id" TYPE_ID,
    "unique_name_de" TEXT,
    "unique_name_en" TEXT,
    "unique_name_es" TEXT,
    "unique_name_fr" TEXT,
    "unique_name_ja" TEXT,
    "unique_name_ko" TEXT,
    "unique_name_ru" TEXT,
    "unique_name_zh" TEXT
);

CREATE TABLE "map_moons_npc_station_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_planets" (
    "key" INTEGER PRIMARY KEY,
    "attributes_height_map1" INTEGER,
    "attributes_height_map2" INTEGER,
    "attributes_population" BOOLEAN,
    "attributes_shader_preset" INTEGER,
    "celestial_index" INTEGER,
    "orbit_id" INTEGER,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "radius" INTEGER,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "statistics_density" REAL,
    "statistics_eccentricity" REAL,
    "statistics_escape_velocity" REAL,
    "statistics_locked" BOOLEAN,
    "statistics_mass_dust" REAL,
    "statistics_mass_gas" REAL,
    "statistics_orbit_period" REAL,
    "statistics_orbit_radius" REAL,
    "statistics_pressure" REAL,
    "statistics_rotation_rate" REAL,
    "statistics_spectral_class" TEXT,
    "statistics_surface_gravity" REAL,
    "statistics_temperature" REAL,
    "type_id" TYPE_ID,
    "unique_name_de" TEXT,
    "unique_name_en" TEXT,
    "unique_name_es" TEXT,
    "unique_name_fr" TEXT,
    "unique_name_ja" TEXT,
    "unique_name_ko" TEXT,
    "unique_name_ru" TEXT,
    "unique_name_zh" TEXT
);

CREATE TABLE "map_planets_asteroid_belt_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_planets_moon_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_planets_npc_station_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_regions" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "faction_id" FACTION_ID,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "nebula_id" INTEGER,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "wormhole_class_id" INTEGER
);

CREATE TABLE "map_regions_constellation_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_secondary_suns" (
    "key" INTEGER PRIMARY KEY,
    "effect_beacon_type_id" INTEGER,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "type_id" TYPE_ID
);

CREATE TABLE "map_solar_systems" (
    "key" SOLAR_SYSTEM_ID PRIMARY KEY,
    "border" BOOLEAN,
    "constellation_id" INTEGER,
    "corridor" BOOLEAN,
    "faction_id" FACTION_ID,
    "fringe" BOOLEAN,
    "hub" BOOLEAN,
    "international" BOOLEAN,
    "luminosity" REAL,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "position2d_x" REAL,
    "position2d_y" REAL,
    "radius" REAL,
    "region_id" INTEGER,
    "regional" BOOLEAN,
    "security_class" TEXT,
    "security_status" REAL,
    "star_id" INTEGER,
    "visual_effect" TEXT,
    "wormhole_class_id" INTEGER
);

CREATE TABLE "map_solar_systems_disallowed_anchor_categories" (
    "parent" SOLAR_SYSTEM_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_solar_systems_disallowed_anchor_groups" (
    "parent" SOLAR_SYSTEM_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_solar_systems_planet_ids" (
    "parent" SOLAR_SYSTEM_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_solar_systems_stargate_ids" (
    "parent" SOLAR_SYSTEM_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "map_stargates" (
    "key" INTEGER PRIMARY KEY,
    "destination_solar_system_id" SOLAR_SYSTEM_ID,
    "destination_stargate_id" INTEGER,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "type_id" TYPE_ID
);

CREATE TABLE "map_stars" (
    "key" INTEGER PRIMARY KEY,
    "radius" INTEGER,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "statistics_age" REAL,
    "statistics_life" REAL,
    "statistics_luminosity" REAL,
    "statistics_spectral_class" TEXT,
    "statistics_temperature" REAL,
    "type_id" TYPE_ID
);

CREATE TABLE "market_groups" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "has_types" BOOLEAN,
    "icon_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "parent_group_id" INTEGER
);

CREATE TABLE "masteries" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "masteries_value" (
    "id" INTEGER PRIMARY KEY,
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL
);

CREATE TABLE "masteries_value_value" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "mercenary_tactical_operations" (
    "key" INTEGER PRIMARY KEY,
    "anarchy_impact" INTEGER,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "development_impact" INTEGER,
    "dungeon_id" INTEGER,
    "infomorph_bonus" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "meta_groups" (
    "key" INTEGER PRIMARY KEY,
    "color_b" REAL,
    "color_g" REAL,
    "color_r" REAL,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon_id" INTEGER,
    "icon_suffix" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "metenox_moon_drill" (
    "key" INTEGER PRIMARY KEY,
    "mining_cycle_time" INTEGER,
    "mining_efficiency" REAL,
    "reagents_consumed_per_cycle" INTEGER
);

CREATE TABLE "military_campaign_objectives" (
    "key" TEXT PRIMARY KEY,
    "annotations_required_enlistment_with_faction_id" INTEGER,
    "annotations_restriction_tooltip_de" TEXT,
    "annotations_restriction_tooltip_en" TEXT,
    "annotations_restriction_tooltip_es" TEXT,
    "annotations_restriction_tooltip_fr" TEXT,
    "annotations_restriction_tooltip_ja" TEXT,
    "annotations_restriction_tooltip_ko" TEXT,
    "annotations_restriction_tooltip_ru" TEXT,
    "annotations_restriction_tooltip_zh" TEXT,
    "annotations_warning1_de" TEXT,
    "annotations_warning1_en" TEXT,
    "annotations_warning1_es" TEXT,
    "annotations_warning1_fr" TEXT,
    "annotations_warning1_ja" TEXT,
    "annotations_warning1_ko" TEXT,
    "annotations_warning1_ru" TEXT,
    "annotations_warning1_zh" TEXT,
    "annotations_warning2_de" TEXT,
    "annotations_warning2_en" TEXT,
    "annotations_warning2_es" TEXT,
    "annotations_warning2_fr" TEXT,
    "annotations_warning2_ja" TEXT,
    "annotations_warning2_ko" TEXT,
    "annotations_warning2_ru" TEXT,
    "annotations_warning2_zh" TEXT,
    "campaign_id" TEXT,
    "career_path" TEXT,
    "contribution_method_configuration_name" TEXT,
    "issuer_corporation_id" CORPORATION_ID,
    "max_progress_per_participant" INTEGER,
    "presenting_character_id" INTEGER,
    "rewards_isk_amount_per_interval" INTEGER,
    "rewards_isk_issuer_corporation_id" CORPORATION_ID,
    "rewards_isk_progress_interval" INTEGER,
    "rewards_lp_amount_per_interval" INTEGER,
    "rewards_lp_issuer_corporation_id" CORPORATION_ID,
    "rewards_lp_progress_interval" INTEGER,
    "rewards_standing_gain_percent_per_interval" REAL,
    "rewards_standing_issuer_faction_id" FACTION_ID,
    "rewards_standing_progress_interval" INTEGER,
    "subtitle_de" TEXT,
    "subtitle_en" TEXT,
    "subtitle_es" TEXT,
    "subtitle_fr" TEXT,
    "subtitle_ja" TEXT,
    "subtitle_ko" TEXT,
    "subtitle_ru" TEXT,
    "subtitle_zh" TEXT,
    "target_progress" INTEGER,
    "title_de" TEXT,
    "title_en" TEXT,
    "title_es" TEXT,
    "title_fr" TEXT,
    "title_ja" TEXT,
    "title_ko" TEXT,
    "title_ru" TEXT,
    "title_zh" TEXT
);

CREATE TABLE "military_campaign_objectives_content_tags" (
    "parent" TEXT NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" TEXT
);

CREATE TABLE "military_campaign_objectives_contribution_method_configuration_parameters" (
    "id" INTEGER PRIMARY KEY,
    "parent" TEXT NOT NULL,
    "idx" INTEGER NOT NULL,
    "key" TEXT
);

CREATE TABLE "military_campaign_objectives_contribution_method_configuration_parameters_matcher_values" (
    "id" INTEGER PRIMARY KEY,
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value_type" TEXT
);

CREATE TABLE "military_campaign_objectives_contribution_method_configuration_parameters_matcher_values_values" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" TEXT
);

CREATE TABLE "military_campaigns" (
    "key" TEXT PRIMARY KEY,
    "annotations_ao_campaign_card_button_image" TEXT,
    "annotations_background_video_loop" TEXT,
    "annotations_briefing_background" TEXT,
    "annotations_briefing_failure_description_de" TEXT,
    "annotations_briefing_failure_description_en" TEXT,
    "annotations_briefing_failure_description_es" TEXT,
    "annotations_briefing_failure_description_fr" TEXT,
    "annotations_briefing_failure_description_ja" TEXT,
    "annotations_briefing_failure_description_ko" TEXT,
    "annotations_briefing_failure_description_ru" TEXT,
    "annotations_briefing_failure_description_zh" TEXT,
    "annotations_briefing_failure_header_de" TEXT,
    "annotations_briefing_failure_header_en" TEXT,
    "annotations_briefing_failure_header_es" TEXT,
    "annotations_briefing_failure_header_fr" TEXT,
    "annotations_briefing_failure_header_ja" TEXT,
    "annotations_briefing_failure_header_ko" TEXT,
    "annotations_briefing_failure_header_ru" TEXT,
    "annotations_briefing_failure_header_zh" TEXT,
    "annotations_briefing_final_words_de" TEXT,
    "annotations_briefing_final_words_en" TEXT,
    "annotations_briefing_final_words_es" TEXT,
    "annotations_briefing_final_words_fr" TEXT,
    "annotations_briefing_final_words_ja" TEXT,
    "annotations_briefing_final_words_ko" TEXT,
    "annotations_briefing_final_words_ru" TEXT,
    "annotations_briefing_final_words_zh" TEXT,
    "annotations_briefing_foreground" TEXT,
    "annotations_briefing_goal_description_de" TEXT,
    "annotations_briefing_goal_description_en" TEXT,
    "annotations_briefing_goal_description_es" TEXT,
    "annotations_briefing_goal_description_fr" TEXT,
    "annotations_briefing_goal_description_ja" TEXT,
    "annotations_briefing_goal_description_ko" TEXT,
    "annotations_briefing_goal_description_ru" TEXT,
    "annotations_briefing_goal_description_zh" TEXT,
    "annotations_briefing_header_de" TEXT,
    "annotations_briefing_header_en" TEXT,
    "annotations_briefing_header_es" TEXT,
    "annotations_briefing_header_fr" TEXT,
    "annotations_briefing_header_ja" TEXT,
    "annotations_briefing_header_ko" TEXT,
    "annotations_briefing_header_ru" TEXT,
    "annotations_briefing_header_zh" TEXT,
    "annotations_briefing_middleground" TEXT,
    "annotations_briefing_success_description_de" TEXT,
    "annotations_briefing_success_description_en" TEXT,
    "annotations_briefing_success_description_es" TEXT,
    "annotations_briefing_success_description_fr" TEXT,
    "annotations_briefing_success_description_ja" TEXT,
    "annotations_briefing_success_description_ko" TEXT,
    "annotations_briefing_success_description_ru" TEXT,
    "annotations_briefing_success_description_zh" TEXT,
    "annotations_briefing_success_header_de" TEXT,
    "annotations_briefing_success_header_en" TEXT,
    "annotations_briefing_success_header_es" TEXT,
    "annotations_briefing_success_header_fr" TEXT,
    "annotations_briefing_success_header_ja" TEXT,
    "annotations_briefing_success_header_ko" TEXT,
    "annotations_briefing_success_header_ru" TEXT,
    "annotations_briefing_success_header_zh" TEXT,
    "annotations_campaign_set" TEXT,
    "annotations_dashboard_ambient_background" TEXT,
    "annotations_dashboard_background" TEXT,
    "annotations_dashboard_foreground" TEXT,
    "annotations_dashboard_middleground" TEXT,
    "annotations_finished_campaign_ended_de" TEXT,
    "annotations_finished_campaign_ended_en" TEXT,
    "annotations_finished_campaign_ended_es" TEXT,
    "annotations_finished_campaign_ended_fr" TEXT,
    "annotations_finished_campaign_ended_ja" TEXT,
    "annotations_finished_campaign_ended_ko" TEXT,
    "annotations_finished_campaign_ended_ru" TEXT,
    "annotations_finished_campaign_ended_zh" TEXT,
    "annotations_finished_failure_description_de" TEXT,
    "annotations_finished_failure_description_en" TEXT,
    "annotations_finished_failure_description_es" TEXT,
    "annotations_finished_failure_description_fr" TEXT,
    "annotations_finished_failure_description_ja" TEXT,
    "annotations_finished_failure_description_ko" TEXT,
    "annotations_finished_failure_description_ru" TEXT,
    "annotations_finished_failure_description_zh" TEXT,
    "annotations_finished_resolution_state_failure_de" TEXT,
    "annotations_finished_resolution_state_failure_en" TEXT,
    "annotations_finished_resolution_state_failure_es" TEXT,
    "annotations_finished_resolution_state_failure_fr" TEXT,
    "annotations_finished_resolution_state_failure_ja" TEXT,
    "annotations_finished_resolution_state_failure_ko" TEXT,
    "annotations_finished_resolution_state_failure_ru" TEXT,
    "annotations_finished_resolution_state_failure_zh" TEXT,
    "annotations_finished_resolution_state_success_de" TEXT,
    "annotations_finished_resolution_state_success_en" TEXT,
    "annotations_finished_resolution_state_success_es" TEXT,
    "annotations_finished_resolution_state_success_fr" TEXT,
    "annotations_finished_resolution_state_success_ja" TEXT,
    "annotations_finished_resolution_state_success_ko" TEXT,
    "annotations_finished_resolution_state_success_ru" TEXT,
    "annotations_finished_resolution_state_success_zh" TEXT,
    "annotations_finished_success_description_de" TEXT,
    "annotations_finished_success_description_en" TEXT,
    "annotations_finished_success_description_es" TEXT,
    "annotations_finished_success_description_fr" TEXT,
    "annotations_finished_success_description_ja" TEXT,
    "annotations_finished_success_description_ko" TEXT,
    "annotations_finished_success_description_ru" TEXT,
    "annotations_finished_success_description_zh" TEXT,
    "annotations_foreground_video_intro" TEXT,
    "annotations_foreground_video_loop" TEXT,
    "annotations_foreground_video_outro" TEXT,
    "annotations_map_focus_entity_id" INTEGER,
    "annotations_map_header_de" TEXT,
    "annotations_map_header_en" TEXT,
    "annotations_map_header_es" TEXT,
    "annotations_map_header_fr" TEXT,
    "annotations_map_header_ja" TEXT,
    "annotations_map_header_ko" TEXT,
    "annotations_map_header_ru" TEXT,
    "annotations_map_header_zh" TEXT,
    "annotations_map_section1paragraph_de" TEXT,
    "annotations_map_section1paragraph_en" TEXT,
    "annotations_map_section1paragraph_es" TEXT,
    "annotations_map_section1paragraph_fr" TEXT,
    "annotations_map_section1paragraph_ja" TEXT,
    "annotations_map_section1paragraph_ko" TEXT,
    "annotations_map_section1paragraph_ru" TEXT,
    "annotations_map_section1paragraph_zh" TEXT,
    "annotations_map_section1title_de" TEXT,
    "annotations_map_section1title_en" TEXT,
    "annotations_map_section1title_es" TEXT,
    "annotations_map_section1title_fr" TEXT,
    "annotations_map_section1title_ja" TEXT,
    "annotations_map_section1title_ko" TEXT,
    "annotations_map_section1title_ru" TEXT,
    "annotations_map_section1title_zh" TEXT,
    "annotations_map_section2paragraph_de" TEXT,
    "annotations_map_section2paragraph_en" TEXT,
    "annotations_map_section2paragraph_es" TEXT,
    "annotations_map_section2paragraph_fr" TEXT,
    "annotations_map_section2paragraph_ja" TEXT,
    "annotations_map_section2paragraph_ko" TEXT,
    "annotations_map_section2paragraph_ru" TEXT,
    "annotations_map_section2paragraph_zh" TEXT,
    "annotations_map_section2title_de" TEXT,
    "annotations_map_section2title_en" TEXT,
    "annotations_map_section2title_es" TEXT,
    "annotations_map_section2title_fr" TEXT,
    "annotations_map_section2title_ja" TEXT,
    "annotations_map_section2title_ko" TEXT,
    "annotations_map_section2title_ru" TEXT,
    "annotations_map_section2title_zh" TEXT,
    "annotations_map_section3paragraph_de" TEXT,
    "annotations_map_section3paragraph_en" TEXT,
    "annotations_map_section3paragraph_es" TEXT,
    "annotations_map_section3paragraph_fr" TEXT,
    "annotations_map_section3paragraph_ja" TEXT,
    "annotations_map_section3paragraph_ko" TEXT,
    "annotations_map_section3paragraph_ru" TEXT,
    "annotations_map_section3paragraph_zh" TEXT,
    "annotations_map_section3title_de" TEXT,
    "annotations_map_section3title_en" TEXT,
    "annotations_map_section3title_es" TEXT,
    "annotations_map_section3title_fr" TEXT,
    "annotations_map_section3title_ja" TEXT,
    "annotations_map_section3title_ko" TEXT,
    "annotations_map_section3title_ru" TEXT,
    "annotations_map_section3title_zh" TEXT,
    "annotations_map_subheader_de" TEXT,
    "annotations_map_subheader_en" TEXT,
    "annotations_map_subheader_es" TEXT,
    "annotations_map_subheader_fr" TEXT,
    "annotations_map_subheader_ja" TEXT,
    "annotations_map_subheader_ko" TEXT,
    "annotations_map_subheader_ru" TEXT,
    "annotations_map_subheader_zh" TEXT,
    "annotations_map_title_de" TEXT,
    "annotations_map_title_en" TEXT,
    "annotations_map_title_es" TEXT,
    "annotations_map_title_fr" TEXT,
    "annotations_map_title_ja" TEXT,
    "annotations_map_title_ko" TEXT,
    "annotations_map_title_ru" TEXT,
    "annotations_map_title_zh" TEXT,
    "annotations_middleground_video_intro" TEXT,
    "annotations_middleground_video_loop" TEXT,
    "annotations_middleground_video_outro" TEXT,
    "annotations_presenting_character_name_de" TEXT,
    "annotations_presenting_character_name_en" TEXT,
    "annotations_presenting_character_name_es" TEXT,
    "annotations_presenting_character_name_fr" TEXT,
    "annotations_presenting_character_name_ja" TEXT,
    "annotations_presenting_character_name_ko" TEXT,
    "annotations_presenting_character_name_ru" TEXT,
    "annotations_presenting_character_name_zh" TEXT,
    "annotations_presenting_character_subtitle_de" TEXT,
    "annotations_presenting_character_subtitle_en" TEXT,
    "annotations_presenting_character_subtitle_es" TEXT,
    "annotations_presenting_character_subtitle_fr" TEXT,
    "annotations_presenting_character_subtitle_ja" TEXT,
    "annotations_presenting_character_subtitle_ko" TEXT,
    "annotations_presenting_character_subtitle_ru" TEXT,
    "annotations_presenting_character_subtitle_zh" TEXT,
    "annotations_presenting_character_texture_path" TEXT,
    "annotations_race" TEXT,
    "annotations_theme_pack" TEXT,
    "annotations_tow_campaign_card_button_image" TEXT,
    "issuer_faction_id" FACTION_ID,
    "subtitle_de" TEXT,
    "subtitle_en" TEXT,
    "subtitle_es" TEXT,
    "subtitle_fr" TEXT,
    "subtitle_ja" TEXT,
    "subtitle_ko" TEXT,
    "subtitle_ru" TEXT,
    "subtitle_zh" TEXT,
    "target_progress" INTEGER,
    "title_de" TEXT,
    "title_en" TEXT,
    "title_es" TEXT,
    "title_fr" TEXT,
    "title_ja" TEXT,
    "title_ko" TEXT,
    "title_ru" TEXT,
    "title_zh" TEXT
);

CREATE TABLE "missions" (
    "key" INTEGER PRIMARY KEY,
    "agent_type_id" INTEGER,
    "corporation_id" CORPORATION_ID,
    "courier_mission_objective_quantity" INTEGER,
    "courier_mission_objective_singleton" BOOLEAN,
    "courier_mission_objective_type_id" INTEGER,
    "expiration_time" INTEGER,
    "faction_id" FACTION_ID,
    "has_standing_rewards" BOOLEAN,
    "initial_agent_gift_quantity" INTEGER,
    "initial_agent_gift_type_id" INTEGER,
    "kill_mission_drop_item_in_mission_container" INTEGER,
    "kill_mission_dungeon_id" INTEGER,
    "kill_mission_objective_quantity" INTEGER,
    "kill_mission_objective_type_id" INTEGER,
    "mission_rewards_bonus_reward_reward_quantity" INTEGER,
    "mission_rewards_bonus_reward_reward_type_id" INTEGER,
    "mission_rewards_bonus_time_interval" INTEGER,
    "mission_rewards_reward_reward_quantity" INTEGER,
    "mission_rewards_reward_reward_type_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "missions_extra_standings" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "missions_messages" (
    "parent" INTEGER NOT NULL,
    "key" TEXT NOT NULL,
    "de" TEXT,
    "en" TEXT,
    "es" TEXT,
    "fr" TEXT,
    "ja" TEXT,
    "ko" TEXT,
    "ru" TEXT,
    "zh" TEXT
);

CREATE TABLE "notification_types" (
    "key" INTEGER PRIMARY KEY,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "internal_name" TEXT
);

CREATE TABLE "npc_characters" (
    "key" INTEGER PRIMARY KEY,
    "agent_agent_type_id" INTEGER,
    "agent_division_id" INTEGER,
    "agent_is_locator" BOOLEAN,
    "agent_level" INTEGER,
    "ancestry_id" INTEGER,
    "bloodline_id" BLOODLINE_ID,
    "career_id" INTEGER,
    "ceo" BOOLEAN,
    "corporation_id" CORPORATION_ID,
    "description" TEXT,
    "gender" BOOLEAN,
    "location_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "race_id" RACE_ID,
    "school_id" INTEGER,
    "speciality_id" INTEGER,
    "start_date" TEXT,
    "unique_name" BOOLEAN
);

CREATE TABLE "npc_characters_skills" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "type_id" TYPE_ID
);

CREATE TABLE "npc_corporation_divisions" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "display_name" TEXT,
    "internal_name" TEXT,
    "leader_type_name_de" TEXT,
    "leader_type_name_en" TEXT,
    "leader_type_name_es" TEXT,
    "leader_type_name_fr" TEXT,
    "leader_type_name_ja" TEXT,
    "leader_type_name_ko" TEXT,
    "leader_type_name_ru" TEXT,
    "leader_type_name_zh" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "npc_corporations" (
    "key" CORPORATION_ID PRIMARY KEY,
    "ceo_id" INTEGER,
    "deleted" BOOLEAN,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "enemy_id" INTEGER,
    "extent" TEXT,
    "faction_id" FACTION_ID,
    "friend_id" INTEGER,
    "has_player_personnel_manager" BOOLEAN,
    "icon_id" INTEGER,
    "initial_price" INTEGER,
    "main_activity_id" INTEGER,
    "member_limit" INTEGER,
    "min_security" REAL,
    "minimum_join_standing" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "race_id" RACE_ID,
    "secondary_activity_id" INTEGER,
    "send_char_termination_message" BOOLEAN,
    "shares" INTEGER,
    "size" TEXT,
    "size_factor" REAL,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "station_id" STATION_ID,
    "tax_rate" REAL,
    "ticker_name" TEXT,
    "unique_name" BOOLEAN
);

CREATE TABLE "npc_corporations_allowed_member_races" (
    "parent" CORPORATION_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "npc_corporations_corporation_trades" (
    "parent" CORPORATION_ID NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "npc_corporations_divisions" (
    "parent" CORPORATION_ID NOT NULL,
    "key" INTEGER NOT NULL,
    "division_number" INTEGER,
    "leader_id" INTEGER,
    "size" INTEGER
);

CREATE TABLE "npc_corporations_exchange_rates" (
    "parent" CORPORATION_ID NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "npc_corporations_investors" (
    "parent" CORPORATION_ID NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "npc_corporations_lp_offer_tables" (
    "parent" CORPORATION_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "npc_stations" (
    "key" STATION_ID PRIMARY KEY,
    "celestial_index" INTEGER,
    "operation_id" INTEGER,
    "orbit_id" INTEGER,
    "orbit_index" INTEGER,
    "owner_id" INTEGER,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "reprocessing_efficiency" REAL,
    "reprocessing_hangar_flag" INTEGER,
    "reprocessing_stations_take" REAL,
    "solar_system_id" SOLAR_SYSTEM_ID,
    "type_id" TYPE_ID,
    "use_operation_name" BOOLEAN
);

CREATE TABLE "planet_resources" (
    "key" INTEGER PRIMARY KEY,
    "power" INTEGER,
    "reagent_amount_per_cycle" INTEGER,
    "reagent_cycle_period" INTEGER,
    "reagent_secured_capacity" INTEGER,
    "reagent_type_id" INTEGER,
    "reagent_unsecured_capacity" INTEGER,
    "workforce" INTEGER
);

CREATE TABLE "planet_schematics" (
    "key" INTEGER PRIMARY KEY,
    "cycle_time" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "planet_schematics_pins" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "planet_schematics_types" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "is_input" BOOLEAN,
    "quantity" INTEGER
);

CREATE TABLE "proximity_trap" (
    "key" INTEGER PRIMARY KEY,
    "dbuff_duration" INTEGER,
    "force_decloak_duration" INTEGER,
    "reset_delay" INTEGER,
    "show_perimeter_lights" BOOLEAN,
    "trigger_delay" INTEGER,
    "trigger_filter_type_list_id" INTEGER,
    "trigger_range" INTEGER
);

CREATE TABLE "proximity_trap_dbuffs" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "races" (
    "key" RACE_ID PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon_id" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "ship_type_id" INTEGER
);

CREATE TABLE "races_skills" (
    "parent" RACE_ID NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "school_map" (
    "key" INTEGER PRIMARY KEY,
    "school_id" INTEGER,
    "solar_system_id" SOLAR_SYSTEM_ID
);

CREATE TABLE "schools" (
    "key" INTEGER PRIMARY KEY,
    "career_id" INTEGER,
    "character_description_de" TEXT,
    "character_description_en" TEXT,
    "character_description_es" TEXT,
    "character_description_fr" TEXT,
    "character_description_ja" TEXT,
    "character_description_ko" TEXT,
    "character_description_ru" TEXT,
    "character_description_zh" TEXT,
    "corporation_id" CORPORATION_ID,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon_id" INTEGER,
    "is_starter_space_school" BOOLEAN,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "race_id" RACE_ID,
    "title_de" TEXT,
    "title_en" TEXT,
    "title_es" TEXT,
    "title_fr" TEXT,
    "title_ja" TEXT,
    "title_ko" TEXT,
    "title_ru" TEXT,
    "title_zh" TEXT
);

CREATE TABLE "schools_career_agents" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "schools_starting_stations" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "ship_tree_elements" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "ship_tree_factions" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon" TEXT
);

CREATE TABLE "ship_tree_factions_elements" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "ship_tree_groups" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "icon" TEXT,
    "icon_large" TEXT,
    "icon_small" TEXT,
    "icon_small_npc" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "ship_tree_groups_elements" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "ship_tree_groups_pre_req_skills" (
    "id" INTEGER PRIMARY KEY,
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL
);

CREATE TABLE "ship_tree_groups_pre_req_skills_skills" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "display" BOOLEAN,
    "level" INTEGER
);

CREATE TABLE "skill_plans" (
    "key" INTEGER PRIMARY KEY,
    "career_path_id" INTEGER,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "faction_id" FACTION_ID,
    "internal_name" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "npc_corporation_division" INTEGER
);

CREATE TABLE "skill_plans_milestones" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "skill_plans_skill_requirements" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "level" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "skin_licenses" (
    "key" INTEGER PRIMARY KEY,
    "duration" INTEGER,
    "is_single_use" BOOLEAN,
    "license_type_id" INTEGER,
    "skin_id" INTEGER
);

CREATE TABLE "skin_materials" (
    "key" INTEGER PRIMARY KEY,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "material_set_id" INTEGER
);

CREATE TABLE "skinr_component_categories" (
    "key" INTEGER PRIMARY KEY,
    "name" TEXT
);

CREATE TABLE "skinr_component_point_values" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "skinr_component_point_values_value" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "skinr_component_rarities" (
    "key" INTEGER PRIMARY KEY,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "rank" INTEGER
);

CREATE TABLE "skinr_components" (
    "key" INTEGER PRIMARY KEY,
    "category" INTEGER,
    "finish" TEXT,
    "icon_file" TEXT,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "projection_type_u" TEXT,
    "projection_type_v" TEXT,
    "published" BOOLEAN,
    "rarity" INTEGER,
    "resource_file" TEXT,
    "sequence_binder_count" INTEGER,
    "sequence_binder_item_type_id" INTEGER
);

CREATE TABLE "skinr_components_associated_type_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "license_uses_granted" INTEGER,
    "type_id" TYPE_ID
);

CREATE TABLE "skinr_slot_categories" (
    "key" INTEGER PRIMARY KEY,
    "name" TEXT
);

CREATE TABLE "skinr_slot_configurations" (
    "key" INTEGER PRIMARY KEY,
    "allow_all_ships" BOOLEAN,
    "name" TEXT,
    "priority" INTEGER
);

CREATE TABLE "skinr_slot_configurations_config" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "skinr_slot_configurations_ships" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "skinr_slot_names" (
    "key" INTEGER PRIMARY KEY,
    "name" TEXT
);

CREATE TABLE "skinr_slots" (
    "key" INTEGER PRIMARY KEY,
    "category" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT
);

CREATE TABLE "skinr_slots_allowed_design_component_categories" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "skinr_slots_to_materials" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "skinr_slots_to_materials_value" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "material_id" INTEGER,
    "slot_id" INTEGER
);

CREATE TABLE "skinr_tier_thresholds" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "skinr_tier_thresholds_value" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "skins" (
    "key" INTEGER PRIMARY KEY,
    "allow_ccp_devs" BOOLEAN,
    "internal_name" TEXT,
    "is_structure_skin" BOOLEAN,
    "skin_material_id" INTEGER,
    "visible_serenity" BOOLEAN,
    "visible_tranquility" BOOLEAN
);

CREATE TABLE "skins_types" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "sovereignty_upgrades" (
    "key" INTEGER PRIMARY KEY,
    "fuel_hourly_upkeep" INTEGER,
    "fuel_startup_cost" INTEGER,
    "fuel_type_id" INTEGER,
    "mutually_exclusive_group" TEXT,
    "power_allocation" INTEGER,
    "power_production" INTEGER,
    "workforce_allocation" INTEGER,
    "workforce_production" INTEGER
);

CREATE TABLE "station_operations" (
    "key" INTEGER PRIMARY KEY,
    "activity_id" INTEGER,
    "border" REAL,
    "corridor" REAL,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "fringe" REAL,
    "hub" REAL,
    "manufacturing_factor" REAL,
    "operation_name_de" TEXT,
    "operation_name_en" TEXT,
    "operation_name_es" TEXT,
    "operation_name_fr" TEXT,
    "operation_name_ja" TEXT,
    "operation_name_ko" TEXT,
    "operation_name_ru" TEXT,
    "operation_name_zh" TEXT,
    "ratio" REAL,
    "research_factor" REAL
);

CREATE TABLE "station_operations_services" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "station_operations_station_types" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "station_services" (
    "key" INTEGER PRIMARY KEY,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "service_name_de" TEXT,
    "service_name_en" TEXT,
    "service_name_es" TEXT,
    "service_name_fr" TEXT,
    "service_name_ja" TEXT,
    "service_name_ko" TEXT,
    "service_name_ru" TEXT,
    "service_name_zh" TEXT
);

CREATE TABLE "station_standings_restrictions" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "station_standings_restrictions_services" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "system_dbuff_emitters" (
    "key" INTEGER PRIMARY KEY,
    "duration" INTEGER,
    "exclude_protected" BOOLEAN,
    "interval" INTEGER
);

CREATE TABLE "system_dbuff_emitters_dbuffs" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "system_wide_effects" (
    "key" INTEGER PRIMARY KEY,
    "eligible_type_list_id" INTEGER,
    "environment_type_id" INTEGER
);

CREATE TABLE "system_wide_effects_dbuffs" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" REAL
);

CREATE TABLE "translation_languages" (
    "key" TEXT PRIMARY KEY,
    "name" TEXT
);

CREATE TABLE "type_bonus" (
    "key" TYPE_ID PRIMARY KEY,
    "icon_id" INTEGER
);

CREATE TABLE "type_bonus_misc_bonuses" (
    "parent" TYPE_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "bonus" REAL,
    "bonus_text_de" TEXT,
    "bonus_text_en" TEXT,
    "bonus_text_es" TEXT,
    "bonus_text_fr" TEXT,
    "bonus_text_ja" TEXT,
    "bonus_text_ko" TEXT,
    "bonus_text_ru" TEXT,
    "bonus_text_zh" TEXT,
    "importance" INTEGER,
    "is_positive" BOOLEAN,
    "unit_id" INTEGER
);

CREATE TABLE "type_bonus_role_bonuses" (
    "parent" TYPE_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "bonus" REAL,
    "bonus_text_de" TEXT,
    "bonus_text_en" TEXT,
    "bonus_text_es" TEXT,
    "bonus_text_fr" TEXT,
    "bonus_text_ja" TEXT,
    "bonus_text_ko" TEXT,
    "bonus_text_ru" TEXT,
    "bonus_text_zh" TEXT,
    "importance" INTEGER,
    "unit_id" INTEGER
);

CREATE TABLE "type_bonus_types" (
    "id" INTEGER PRIMARY KEY,
    "parent" TYPE_ID NOT NULL,
    "key" INTEGER NOT NULL
);

CREATE TABLE "type_bonus_types_value" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "bonus" REAL,
    "bonus_text_de" TEXT,
    "bonus_text_en" TEXT,
    "bonus_text_es" TEXT,
    "bonus_text_fr" TEXT,
    "bonus_text_ja" TEXT,
    "bonus_text_ko" TEXT,
    "bonus_text_ru" TEXT,
    "bonus_text_zh" TEXT,
    "importance" INTEGER,
    "unit_id" INTEGER
);

CREATE TABLE "type_dogma" (
    "key" TYPE_ID PRIMARY KEY
);

CREATE TABLE "type_dogma_dogma_attributes" (
    "parent" TYPE_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "attribute_id" INTEGER,
    "value" REAL
);

CREATE TABLE "type_dogma_dogma_effects" (
    "parent" TYPE_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "effect_id" INTEGER,
    "is_default" BOOLEAN
);

CREATE TABLE "type_elements" (
    "key" INTEGER PRIMARY KEY
);

CREATE TABLE "type_elements_elements" (
    "parent" INTEGER NOT NULL,
    "key" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "type_lists" (
    "key" INTEGER PRIMARY KEY,
    "display_description_de" TEXT,
    "display_description_en" TEXT,
    "display_description_es" TEXT,
    "display_description_fr" TEXT,
    "display_description_ja" TEXT,
    "display_description_ko" TEXT,
    "display_description_ru" TEXT,
    "display_description_zh" TEXT,
    "display_name_de" TEXT,
    "display_name_en" TEXT,
    "display_name_es" TEXT,
    "display_name_fr" TEXT,
    "display_name_ja" TEXT,
    "display_name_ko" TEXT,
    "display_name_ru" TEXT,
    "display_name_zh" TEXT,
    "name" TEXT
);

CREATE TABLE "type_lists_excluded_category_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "type_lists_excluded_group_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "type_lists_excluded_type_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "type_lists_included_category_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "type_lists_included_group_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "type_lists_included_type_ids" (
    "parent" INTEGER NOT NULL,
    "idx" INTEGER NOT NULL,
    "value" INTEGER
);

CREATE TABLE "type_materials" (
    "key" TYPE_ID PRIMARY KEY
);

CREATE TABLE "type_materials_materials" (
    "parent" TYPE_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "material_type_id" INTEGER,
    "quantity" INTEGER
);

CREATE TABLE "type_materials_randomized_materials" (
    "parent" TYPE_ID NOT NULL,
    "idx" INTEGER NOT NULL,
    "material_type_id" INTEGER,
    "quantity_max" INTEGER,
    "quantity_min" INTEGER
);

CREATE TABLE "types" (
    "key" TYPE_ID PRIMARY KEY,
    "base_price" REAL,
    "capacity" REAL,
    "description_de" TEXT,
    "description_en" TEXT,
    "description_es" TEXT,
    "description_fr" TEXT,
    "description_ja" TEXT,
    "description_ko" TEXT,
    "description_ru" TEXT,
    "description_zh" TEXT,
    "faction_id" FACTION_ID,
    "graphic_id" INTEGER,
    "group_id" INTEGER,
    "icon_id" INTEGER,
    "is_dynamic_type" BOOLEAN,
    "is_repackable" BOOLEAN,
    "market_group_id" INTEGER,
    "mass" REAL,
    "meta_group_id" INTEGER,
    "meta_level" INTEGER,
    "name_de" TEXT,
    "name_en" TEXT,
    "name_es" TEXT,
    "name_fr" TEXT,
    "name_ja" TEXT,
    "name_ko" TEXT,
    "name_ru" TEXT,
    "name_zh" TEXT,
    "packaged_volume" REAL,
    "portion_size" INTEGER,
    "published" BOOLEAN,
    "race_id" RACE_ID,
    "radius" REAL,
    "ship_tree_group_id" INTEGER,
    "sound_id" INTEGER,
    "tech_level" INTEGER,
    "variation_parent_type_id" INTEGER,
    "volume" REAL
);

CREATE INDEX "applied_proximity_effects_dbuffs_parent" ON "applied_proximity_effects_dbuffs" ("parent");
CREATE INDEX "blueprints_activities_copying_materials_parent" ON "blueprints_activities_copying_materials" ("parent");
CREATE INDEX "blueprints_activities_copying_skills_parent" ON "blueprints_activities_copying_skills" ("parent");
CREATE INDEX "blueprints_activities_invention_materials_parent" ON "blueprints_activities_invention_materials" ("parent");
CREATE INDEX "blueprints_activities_invention_products_parent" ON "blueprints_activities_invention_products" ("parent");
CREATE INDEX "blueprints_activities_invention_skills_parent" ON "blueprints_activities_invention_skills" ("parent");
CREATE INDEX "blueprints_activities_manufacturing_materials_parent" ON "blueprints_activities_manufacturing_materials" ("parent");
CREATE INDEX "blueprints_activities_manufacturing_products_parent" ON "blueprints_activities_manufacturing_products" ("parent");
CREATE INDEX "blueprints_activities_manufacturing_skills_parent" ON "blueprints_activities_manufacturing_skills" ("parent");
CREATE INDEX "blueprints_activities_reaction_materials_parent" ON "blueprints_activities_reaction_materials" ("parent");
CREATE INDEX "blueprints_activities_reaction_products_parent" ON "blueprints_activities_reaction_products" ("parent");
CREATE INDEX "blueprints_activities_reaction_skills_parent" ON "blueprints_activities_reaction_skills" ("parent");
CREATE INDEX "blueprints_activities_research_material_materials_parent" ON "blueprints_activities_research_material_materials" ("parent");
CREATE INDEX "blueprints_activities_research_material_skills_parent" ON "blueprints_activities_research_material_skills" ("parent");
CREATE INDEX "blueprints_activities_research_time_materials_parent" ON "blueprints_activities_research_time_materials" ("parent");
CREATE INDEX "blueprints_activities_research_time_skills_parent" ON "blueprints_activities_research_time_skills" ("parent");
CREATE INDEX "certificates_recommended_for_parent" ON "certificates_recommended_for" ("parent");
CREATE INDEX "certificates_skill_types_parent" ON "certificates_skill_types" ("parent");
CREATE INDEX "clone_grades_skills_parent" ON "clone_grades_skills" ("parent");
CREATE INDEX "contraband_types_factions_parent" ON "contraband_types_factions" ("parent");
CREATE INDEX "control_tower_resources_resources_parent" ON "control_tower_resources_resources" ("parent");
CREATE INDEX "corporation_roles_role_group_ids_parent" ON "corporation_roles_role_group_ids" ("parent");
CREATE INDEX "dbuff_collections_item_modifiers_parent" ON "dbuff_collections_item_modifiers" ("parent");
CREATE INDEX "dbuff_collections_location_group_modifiers_parent" ON "dbuff_collections_location_group_modifiers" ("parent");
CREATE INDEX "dbuff_collections_location_modifiers_parent" ON "dbuff_collections_location_modifiers" ("parent");
CREATE INDEX "dbuff_collections_location_required_skill_modifiers_parent" ON "dbuff_collections_location_required_skill_modifiers" ("parent");
CREATE INDEX "dogma_effects_modifier_info_parent" ON "dogma_effects_modifier_info" ("parent");
CREATE INDEX "dungeons_allowed_ships_list_parent" ON "dungeons_allowed_ships_list" ("parent");
CREATE INDEX "dynamic_item_attributes_attribute_ids_parent" ON "dynamic_item_attributes_attribute_ids" ("parent");
CREATE INDEX "dynamic_item_attributes_input_output_mapping_parent" ON "dynamic_item_attributes_input_output_mapping" ("parent");
CREATE INDEX "dynamic_item_attributes_input_output_mapping_applicable_types_parent" ON "dynamic_item_attributes_input_output_mapping_applicable_types" ("parent");
CREATE INDEX "epic_arcs_missions_parent" ON "epic_arcs_missions" ("parent");
CREATE INDEX "epic_arcs_missions_next_missions_parent" ON "epic_arcs_missions_next_missions" ("parent");
CREATE INDEX "expert_systems_associated_ship_types_parent" ON "expert_systems_associated_ship_types" ("parent");
CREATE INDEX "expert_systems_skills_granted_parent" ON "expert_systems_skills_granted" ("parent");
CREATE INDEX "factions_member_races_parent" ON "factions_member_races" ("parent");
CREATE INDEX "freelance_job_schemas_value_parent" ON "freelance_job_schemas_value" ("parent");
CREATE INDEX "freelance_job_schemas_value_content_tags_parent" ON "freelance_job_schemas_value_content_tags" ("parent");
CREATE INDEX "freelance_job_schemas_value_parameters_parent" ON "freelance_job_schemas_value_parameters" ("parent");
CREATE INDEX "freelance_job_schemas_value_parameters_item_delivery_delivery_location_accepted_value_types_parent" ON "freelance_job_schemas_value_parameters_item_delivery_delivery_location_accepted_value_types" ("parent");
CREATE INDEX "freelance_job_schemas_value_parameters_item_delivery_inventory_type_accepted_value_types_parent" ON "freelance_job_schemas_value_parameters_item_delivery_inventory_type_accepted_value_types" ("parent");
CREATE INDEX "freelance_job_schemas_value_parameters_matcher_accepted_value_types_parent" ON "freelance_job_schemas_value_parameters_matcher_accepted_value_types" ("parent");
CREATE INDEX "graphics_sof_layout_parent" ON "graphics_sof_layout" ("parent");
CREATE INDEX "industry_assembly_lines_details_per_category_parent" ON "industry_assembly_lines_details_per_category" ("parent");
CREATE INDEX "industry_assembly_lines_details_per_group_parent" ON "industry_assembly_lines_details_per_group" ("parent");
CREATE INDEX "industry_assembly_lines_details_per_type_list_parent" ON "industry_assembly_lines_details_per_type_list" ("parent");
CREATE INDEX "industry_installation_types_assembly_lines_parent" ON "industry_installation_types_assembly_lines" ("parent");
CREATE INDEX "industry_modifier_sources_copying_cost_parent" ON "industry_modifier_sources_copying_cost" ("parent");
CREATE INDEX "industry_modifier_sources_copying_time_parent" ON "industry_modifier_sources_copying_time" ("parent");
CREATE INDEX "industry_modifier_sources_invention_cost_parent" ON "industry_modifier_sources_invention_cost" ("parent");
CREATE INDEX "industry_modifier_sources_invention_time_parent" ON "industry_modifier_sources_invention_time" ("parent");
CREATE INDEX "industry_modifier_sources_manufacturing_cost_parent" ON "industry_modifier_sources_manufacturing_cost" ("parent");
CREATE INDEX "industry_modifier_sources_manufacturing_material_parent" ON "industry_modifier_sources_manufacturing_material" ("parent");
CREATE INDEX "industry_modifier_sources_manufacturing_time_parent" ON "industry_modifier_sources_manufacturing_time" ("parent");
CREATE INDEX "industry_modifier_sources_reaction_material_parent" ON "industry_modifier_sources_reaction_material" ("parent");
CREATE INDEX "industry_modifier_sources_reaction_time_parent" ON "industry_modifier_sources_reaction_time" ("parent");
CREATE INDEX "industry_modifier_sources_research_material_cost_parent" ON "industry_modifier_sources_research_material_cost" ("parent");
CREATE INDEX "industry_modifier_sources_research_material_time_parent" ON "industry_modifier_sources_research_material_time" ("parent");
CREATE INDEX "industry_modifier_sources_research_time_cost_parent" ON "industry_modifier_sources_research_time_cost" ("parent");
CREATE INDEX "industry_modifier_sources_research_time_time_parent" ON "industry_modifier_sources_research_time_time" ("parent");
CREATE INDEX "industry_target_filters_category_ids_parent" ON "industry_target_filters_category_ids" ("parent");
CREATE INDEX "industry_target_filters_group_ids_parent" ON "industry_target_filters_group_ids" ("parent");
CREATE INDEX "link_with_ship_dbuffs_parent" ON "link_with_ship_dbuffs" ("parent");
CREATE INDEX "map_constellations_solar_system_ids_parent" ON "map_constellations_solar_system_ids" ("parent");
CREATE INDEX "map_moons_npc_station_ids_parent" ON "map_moons_npc_station_ids" ("parent");
CREATE INDEX "map_planets_asteroid_belt_ids_parent" ON "map_planets_asteroid_belt_ids" ("parent");
CREATE INDEX "map_planets_moon_ids_parent" ON "map_planets_moon_ids" ("parent");
CREATE INDEX "map_planets_npc_station_ids_parent" ON "map_planets_npc_station_ids" ("parent");
CREATE INDEX "map_regions_constellation_ids_parent" ON "map_regions_constellation_ids" ("parent");
CREATE INDEX "map_solar_systems_disallowed_anchor_categories_parent" ON "map_solar_systems_disallowed_anchor_categories" ("parent");
CREATE INDEX "map_solar_systems_disallowed_anchor_groups_parent" ON "map_solar_systems_disallowed_anchor_groups" ("parent");
CREATE INDEX "map_solar_systems_planet_ids_parent" ON "map_solar_systems_planet_ids" ("parent");
CREATE INDEX "map_solar_systems_stargate_ids_parent" ON "map_solar_systems_stargate_ids" ("parent");
CREATE INDEX "masteries_value_parent" ON "masteries_value" ("parent");
CREATE INDEX "masteries_value_value_parent" ON "masteries_value_value" ("parent");
CREATE INDEX "military_campaign_objectives_content_tags_parent" ON "military_campaign_objectives_content_tags" ("parent");
CREATE INDEX "military_campaign_objectives_contribution_method_configuration_parameters_parent" ON "military_campaign_objectives_contribution_method_configuration_parameters" ("parent");
CREATE INDEX "military_campaign_objectives_contribution_method_configuration_parameters_matcher_values_parent" ON "military_campaign_objectives_contribution_method_configuration_parameters_matcher_values" ("parent");
CREATE INDEX "military_campaign_objectives_contribution_method_configuration_parameters_matcher_values_values_parent" ON "military_campaign_objectives_contribution_method_configuration_parameters_matcher_values_values" ("parent");
CREATE INDEX "missions_extra_standings_parent" ON "missions_extra_standings" ("parent");
CREATE INDEX "missions_messages_parent" ON "missions_messages" ("parent");
CREATE INDEX "npc_characters_skills_parent" ON "npc_characters_skills" ("parent");
CREATE INDEX "npc_corporations_allowed_member_races_parent" ON "npc_corporations_allowed_member_races" ("parent");
CREATE INDEX "npc_corporations_corporation_trades_parent" ON "npc_corporations_corporation_trades" ("parent");
CREATE INDEX "npc_corporations_divisions_parent" ON "npc_corporations_divisions" ("parent");
CREATE INDEX "npc_corporations_exchange_rates_parent" ON "npc_corporations_exchange_rates" ("parent");
CREATE INDEX "npc_corporations_investors_parent" ON "npc_corporations_investors" ("parent");
CREATE INDEX "npc_corporations_lp_offer_tables_parent" ON "npc_corporations_lp_offer_tables" ("parent");
CREATE INDEX "planet_schematics_pins_parent" ON "planet_schematics_pins" ("parent");
CREATE INDEX "planet_schematics_types_parent" ON "planet_schematics_types" ("parent");
CREATE INDEX "proximity_trap_dbuffs_parent" ON "proximity_trap_dbuffs" ("parent");
CREATE INDEX "races_skills_parent" ON "races_skills" ("parent");
CREATE INDEX "schools_career_agents_parent" ON "schools_career_agents" ("parent");
CREATE INDEX "schools_starting_stations_parent" ON "schools_starting_stations" ("parent");
CREATE INDEX "ship_tree_factions_elements_parent" ON "ship_tree_factions_elements" ("parent");
CREATE INDEX "ship_tree_groups_elements_parent" ON "ship_tree_groups_elements" ("parent");
CREATE INDEX "ship_tree_groups_pre_req_skills_parent" ON "ship_tree_groups_pre_req_skills" ("parent");
CREATE INDEX "ship_tree_groups_pre_req_skills_skills_parent" ON "ship_tree_groups_pre_req_skills_skills" ("parent");
CREATE INDEX "skill_plans_milestones_parent" ON "skill_plans_milestones" ("parent");
CREATE INDEX "skill_plans_skill_requirements_parent" ON "skill_plans_skill_requirements" ("parent");
CREATE INDEX "skinr_component_point_values_value_parent" ON "skinr_component_point_values_value" ("parent");
CREATE INDEX "skinr_components_associated_type_ids_parent" ON "skinr_components_associated_type_ids" ("parent");
CREATE INDEX "skinr_slot_configurations_config_parent" ON "skinr_slot_configurations_config" ("parent");
CREATE INDEX "skinr_slot_configurations_ships_parent" ON "skinr_slot_configurations_ships" ("parent");
CREATE INDEX "skinr_slots_allowed_design_component_categories_parent" ON "skinr_slots_allowed_design_component_categories" ("parent");
CREATE INDEX "skinr_slots_to_materials_value_parent" ON "skinr_slots_to_materials_value" ("parent");
CREATE INDEX "skinr_tier_thresholds_value_parent" ON "skinr_tier_thresholds_value" ("parent");
CREATE INDEX "skins_types_parent" ON "skins_types" ("parent");
CREATE INDEX "station_operations_services_parent" ON "station_operations_services" ("parent");
CREATE INDEX "station_operations_station_types_parent" ON "station_operations_station_types" ("parent");
CREATE INDEX "station_standings_restrictions_services_parent" ON "station_standings_restrictions_services" ("parent");
CREATE INDEX "system_dbuff_emitters_dbuffs_parent" ON "system_dbuff_emitters_dbuffs" ("parent");
CREATE INDEX "system_wide_effects_dbuffs_parent" ON "system_wide_effects_dbuffs" ("parent");
CREATE INDEX "type_bonus_misc_bonuses_parent" ON "type_bonus_misc_bonuses" ("parent");
CREATE INDEX "type_bonus_role_bonuses_parent" ON "type_bonus_role_bonuses" ("parent");
CREATE INDEX "type_bonus_types_parent" ON "type_bonus_types" ("parent");
CREATE INDEX "type_bonus_types_value_parent" ON "type_bonus_types_value" ("parent");
CREATE INDEX "type_dogma_dogma_attributes_parent" ON "type_dogma_dogma_attributes" ("parent");
CREATE INDEX "type_dogma_dogma_effects_parent" ON "type_dogma_dogma_effects" ("parent");
CREATE INDEX "type_elements_elements_parent" ON "type_elements_elements" ("parent");
CREATE INDEX "type_lists_excluded_category_ids_parent" ON "type_lists_excluded_category_ids" ("parent");
CREATE INDEX "type_lists_excluded_group_ids_parent" ON "type_lists_excluded_group_ids" ("parent");
CREATE INDEX "type_lists_excluded_type_ids_parent" ON "type_lists_excluded_type_ids" ("parent");
CREATE INDEX "type_lists_included_category_ids_parent" ON "type_lists_included_category_ids" ("parent");
CREATE INDEX "type_lists_included_group_ids_parent" ON "type_lists_included_group_ids" ("parent");
CREATE INDEX "type_lists_included_type_ids_parent" ON "type_lists_included_type_ids" ("parent");
CREATE INDEX "type_materials_materials_parent" ON "type_materials_materials" ("parent");
CREATE INDEX "type_materials_randomized_materials_parent" ON "type_materials_randomized_materials" ("parent");
