// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sde

import (
	"time"
)

type Meta struct {
	Build       int64     `json:"build"`
	ReleaseDate time.Time `json:"releaseDate"`
	Schema      string    `json:"schema"`
}
