// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Skill {
    "characterId": number;
    "skillId": number;
    "activeSkillLevel": number;
    "trainedSkillLevel": number;
    "skillpointsInSkill": number;

    /** Creates a new Skill instance. */
    constructor($$source: Partial<Skill> = {}) {
        if (!("characterId" in $$source)) {
            this["characterId"] = 0;
        }
        if (!("skillId" in $$source)) {
            this["skillId"] = 0;
        }
        if (!("activeSkillLevel" in $$source)) {
            this["activeSkillLevel"] = 0;
        }
        if (!("trainedSkillLevel" in $$source)) {
            this["trainedSkillLevel"] = 0;
        }
        if (!("skillpointsInSkill" in $$source)) {
            this["skillpointsInSkill"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     */
    static createFrom($$source: any = {}): Skill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill($$parsedSource as Partial<Skill>);
    }
}
