// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package skills

import (
	"context"
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

const deleteQueue = `-- name: DeleteQueue :exec
DELETE FROM skill_queue WHERE character_id = ?
`

func (q *Queries) DeleteQueue(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteQueue, characterID)
	return err
}

const deleteSkills = `-- name: DeleteSkills :exec
DELETE FROM skills WHERE character_id = ?
`

func (q *Queries) DeleteSkills(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSkills, characterID)
	return err
}

const getAttributes = `-- name: GetAttributes :one
SELECT character_id, charisma, intelligence, memory, perception, willpower, bonus_remaps, last_remap_date, accrued_remap_cooldown_date, fetched_at FROM skill_attributes WHERE character_id = ?
`

func (q *Queries) GetAttributes(ctx context.Context, characterID int64) (SkillAttribute, error) {
	row := q.db.QueryRowContext(ctx, getAttributes, characterID)
	var i SkillAttribute
	err := row.Scan(
		&i.CharacterID,
		&i.Charisma,
		&i.Intelligence,
		&i.Memory,
		&i.Perception,
		&i.Willpower,
		&i.BonusRemaps,
		&i.LastRemapDate,
		&i.AccruedRemapCooldownDate,
		&i.FetchedAt,
	)
	return i, err
}

const getTotals = `-- name: GetTotals :one
SELECT character_id, total_sp, unallocated_sp, fetched_at FROM skill_totals WHERE character_id = ?
`

func (q *Queries) GetTotals(ctx context.Context, characterID int64) (SkillTotal, error) {
	row := q.db.QueryRowContext(ctx, getTotals, characterID)
	var i SkillTotal
	err := row.Scan(
		&i.CharacterID,
		&i.TotalSp,
		&i.UnallocatedSp,
		&i.FetchedAt,
	)
	return i, err
}

const insertQueueEntry = `-- name: InsertQueueEntry :one
INSERT INTO skill_queue (
    character_id, queue_position, skill_id, finished_level, start_date, finish_date,
    training_start_sp, level_start_sp, level_end_sp, fetched_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING character_id, queue_position, skill_id, finished_level, start_date, finish_date, training_start_sp, level_start_sp, level_end_sp, fetched_at
`

type InsertQueueEntryParams struct {
	CharacterID     int64             `json:"characterId"`
	QueuePosition   int64             `json:"queuePosition"`
	SkillID         typeid.Identifier `json:"skillId"`
	FinishedLevel   int64             `json:"finishedLevel"`
	StartDate       *time.Time        `json:"startDate"`
	FinishDate      *time.Time        `json:"finishDate"`
	TrainingStartSp *int64            `json:"trainingStartSp"`
	LevelStartSp    *int64            `json:"levelStartSp"`
	LevelEndSp      *int64            `json:"levelEndSp"`
	FetchedAt       time.Time         `json:"fetchedAt"`
}

func (q *Queries) InsertQueueEntry(ctx context.Context, arg InsertQueueEntryParams) (SkillQueue, error) {
	row := q.db.QueryRowContext(ctx, insertQueueEntry,
		arg.CharacterID,
		arg.QueuePosition,
		arg.SkillID,
		arg.FinishedLevel,
		arg.StartDate,
		arg.FinishDate,
		arg.TrainingStartSp,
		arg.LevelStartSp,
		arg.LevelEndSp,
		arg.FetchedAt,
	)
	var i SkillQueue
	err := row.Scan(
		&i.CharacterID,
		&i.QueuePosition,
		&i.SkillID,
		&i.FinishedLevel,
		&i.StartDate,
		&i.FinishDate,
		&i.TrainingStartSp,
		&i.LevelStartSp,
		&i.LevelEndSp,
		&i.FetchedAt,
	)
	return i, err
}

const insertSkill = `-- name: InsertSkill :one
INSERT INTO skills (character_id, skill_id, active_skill_level, trained_skill_level, skillpoints_in_skill)
VALUES (?, ?, ?, ?, ?)
RETURNING character_id, skill_id, active_skill_level, trained_skill_level, skillpoints_in_skill
`

type InsertSkillParams struct {
	CharacterID        int64 `json:"characterId"`
	SkillID            int64 `json:"skillId"`
	ActiveSkillLevel   int64 `json:"activeSkillLevel"`
	TrainedSkillLevel  int64 `json:"trainedSkillLevel"`
	SkillpointsInSkill int64 `json:"skillpointsInSkill"`
}

func (q *Queries) InsertSkill(ctx context.Context, arg InsertSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, insertSkill,
		arg.CharacterID,
		arg.SkillID,
		arg.ActiveSkillLevel,
		arg.TrainedSkillLevel,
		arg.SkillpointsInSkill,
	)
	var i Skill
	err := row.Scan(
		&i.CharacterID,
		&i.SkillID,
		&i.ActiveSkillLevel,
		&i.TrainedSkillLevel,
		&i.SkillpointsInSkill,
	)
	return i, err
}

const listQueue = `-- name: ListQueue :many
SELECT character_id, queue_position, skill_id, finished_level, start_date, finish_date, training_start_sp, level_start_sp, level_end_sp, fetched_at FROM skill_queue WHERE character_id = ? ORDER BY queue_position
`

func (q *Queries) ListQueue(ctx context.Context, characterID int64) ([]SkillQueue, error) {
	rows, err := q.db.QueryContext(ctx, listQueue, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillQueue
	for rows.Next() {
		var i SkillQueue
		if err := rows.Scan(
			&i.CharacterID,
			&i.QueuePosition,
			&i.SkillID,
			&i.FinishedLevel,
			&i.StartDate,
			&i.FinishDate,
			&i.TrainingStartSp,
			&i.LevelStartSp,
			&i.LevelEndSp,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT character_id, skill_id, active_skill_level, trained_skill_level, skillpoints_in_skill FROM skills WHERE character_id = ? ORDER BY skill_id
`

func (q *Queries) ListSkills(ctx context.Context, characterID int64) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkills, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.CharacterID,
			&i.SkillID,
			&i.ActiveSkillLevel,
			&i.TrainedSkillLevel,
			&i.SkillpointsInSkill,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttributes = `-- name: UpsertAttributes :one
INSERT INTO skill_attributes (
    character_id, charisma, intelligence, memory, perception, willpower,
    bonus_remaps, last_remap_date, accrued_remap_cooldown_date, fetched_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    charisma = excluded.charisma,
    intelligence = excluded.intelligence,
    memory = excluded.memory,
    perception = excluded.perception,
    willpower = excluded.willpower,
    bonus_remaps = excluded.bonus_remaps,
    last_remap_date = excluded.last_remap_date,
    accrued_remap_cooldown_date = excluded.accrued_remap_cooldown_date,
    fetched_at = excluded.fetched_at
RETURNING character_id, charisma, intelligence, memory, perception, willpower, bonus_remaps, last_remap_date, accrued_remap_cooldown_date, fetched_at
`

type UpsertAttributesParams struct {
	CharacterID              int64      `json:"characterId"`
	Charisma                 int64      `json:"charisma"`
	Intelligence             int64      `json:"intelligence"`
	Memory                   int64      `json:"memory"`
	Perception               int64      `json:"perception"`
	Willpower                int64      `json:"willpower"`
	BonusRemaps              *int64     `json:"bonusRemaps"`
	LastRemapDate            *time.Time `json:"lastRemapDate"`
	AccruedRemapCooldownDate *time.Time `json:"accruedRemapCooldownDate"`
	FetchedAt                time.Time  `json:"fetchedAt"`
}

func (q *Queries) UpsertAttributes(ctx context.Context, arg UpsertAttributesParams) (SkillAttribute, error) {
	row := q.db.QueryRowContext(ctx, upsertAttributes,
		arg.CharacterID,
		arg.Charisma,
		arg.Intelligence,
		arg.Memory,
		arg.Perception,
		arg.Willpower,
		arg.BonusRemaps,
		arg.LastRemapDate,
		arg.AccruedRemapCooldownDate,
		arg.FetchedAt,
	)
	var i SkillAttribute
	err := row.Scan(
		&i.CharacterID,
		&i.Charisma,
		&i.Intelligence,
		&i.Memory,
		&i.Perception,
		&i.Willpower,
		&i.BonusRemaps,
		&i.LastRemapDate,
		&i.AccruedRemapCooldownDate,
		&i.FetchedAt,
	)
	return i, err
}

const upsertTotals = `-- name: UpsertTotals :one
INSERT INTO skill_totals (character_id, total_sp, unallocated_sp, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    total_sp = excluded.total_sp,
    unallocated_sp = excluded.unallocated_sp,
    fetched_at = excluded.fetched_at
RETURNING character_id, total_sp, unallocated_sp, fetched_at
`

type UpsertTotalsParams struct {
	CharacterID   int64     `json:"characterId"`
	TotalSp       int64     `json:"totalSp"`
	UnallocatedSp *int64    `json:"unallocatedSp"`
	FetchedAt     time.Time `json:"fetchedAt"`
}

func (q *Queries) UpsertTotals(ctx context.Context, arg UpsertTotalsParams) (SkillTotal, error) {
	row := q.db.QueryRowContext(ctx, upsertTotals,
		arg.CharacterID,
		arg.TotalSp,
		arg.UnallocatedSp,
		arg.FetchedAt,
	)
	var i SkillTotal
	err := row.Scan(
		&i.CharacterID,
		&i.TotalSp,
		&i.UnallocatedSp,
		&i.FetchedAt,
	)
	return i, err
}
