// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package skills

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type Skill struct {
	CharacterID        int64 `json:"characterId"`
	SkillID            int64 `json:"skillId"`
	ActiveSkillLevel   int64 `json:"activeSkillLevel"`
	TrainedSkillLevel  int64 `json:"trainedSkillLevel"`
	SkillpointsInSkill int64 `json:"skillpointsInSkill"`
}

type SkillAttribute struct {
	CharacterID              int64      `json:"characterId"`
	Charisma                 int64      `json:"charisma"`
	Intelligence             int64      `json:"intelligence"`
	Memory                   int64      `json:"memory"`
	Perception               int64      `json:"perception"`
	Willpower                int64      `json:"willpower"`
	BonusRemaps              *int64     `json:"bonusRemaps"`
	LastRemapDate            *time.Time `json:"lastRemapDate"`
	AccruedRemapCooldownDate *time.Time `json:"accruedRemapCooldownDate"`
	FetchedAt                time.Time  `json:"fetchedAt"`
}

type SkillQueue struct {
	CharacterID     int64             `json:"characterId"`
	QueuePosition   int64             `json:"queuePosition"`
	SkillID         typeid.Identifier `json:"skillId"`
	FinishedLevel   int64             `json:"finishedLevel"`
	StartDate       *time.Time        `json:"startDate"`
	FinishDate      *time.Time        `json:"finishDate"`
	TrainingStartSp *int64            `json:"trainingStartSp"`
	LevelStartSp    *int64            `json:"levelStartSp"`
	LevelEndSp      *int64            `json:"levelEndSp"`
	FetchedAt       time.Time         `json:"fetchedAt"`
}

type SkillTotal struct {
	CharacterID   int64     `json:"characterId"`
	TotalSp       int64     `json:"totalSp"`
	UnallocatedSp *int64    `json:"unallocatedSp"`
	FetchedAt     time.Time `json:"fetchedAt"`
}
