// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginLogin is called from the picker window. It will start the SSO flow for the
 * named features and send that window to the SSO; completion is reported through
 * EventChanged.
 */
export function BeginLogin(features: string[]): $CancellablePromise<void> {
    return $Call.ByID(686594795, features);
}

/**
 * Features lists every opt-in feature and the scopes it needs. The frontend diffs
 * them against a character's token scopes to show what is enabled.
 */
export function Features(): $CancellablePromise<$models.FeatureInfo[]> {
    return $Call.ByID(1135145226).then(($result: any) => {
        return $$createType1($result);
    });
}

export function List(): $CancellablePromise<$models.ListRow[]> {
    return $Call.ByID(195734209).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenAddWindow shows the feature picker window.
 */
export function OpenAddWindow(): $CancellablePromise<void> {
    return $Call.ByID(3766459884);
}

export function Remove(characterID: number): $CancellablePromise<void> {
    return $Call.ByID(2604506173, characterID);
}

// Private type creation functions
const $$createType0 = $models.FeatureInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ListRow.createFrom;
const $$createType3 = $Create.Array($$createType2);
