// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Progress of a running task, for a progress bar.
 */
export class Progress {
    "phase": string;
    "item": string;
    "done": number;

    /**
     * Total is 0 when unknown.
     */
    "total": number;

    /** Creates a new Progress instance. */
    constructor($$source: Partial<Progress> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("item" in $$source)) {
            this["item"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Progress instance from a string or object.
     */
    static createFrom($$source: any = {}): Progress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Progress($$parsedSource as Partial<Progress>);
    }
}

/**
 * ProgressEvent is what Options.OnProgress receives for tasks with WithProgress.
 */
export class ProgressEvent {
    "key": string;
    "subject": string;

    /**
     * State is ProgressStart, ProgressUpdate or ProgressDone.
     */
    "state": string;
    "progress": Progress;

    /**
     * Error is the run's error, on done only.
     */
    "error": string;

    /** Creates a new ProgressEvent instance. */
    constructor($$source: Partial<ProgressEvent> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = (new Progress());
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgressEvent {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("progress" in $$parsedSource) {
            $$parsedSource["progress"] = $$createField3_0($$parsedSource["progress"]);
        }
        return new ProgressEvent($$parsedSource as Partial<ProgressEvent>);
    }
}

// Private type creation functions
const $$createType0 = Progress.createFrom;
