// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package token

import (
	"context"
)

const getScopes = `-- name: GetScopes :one
SELECT scopes FROM tokens WHERE character_id = ?
`

func (q *Queries) GetScopes(ctx context.Context, characterID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getScopes, characterID)
	var scopes string
	err := row.Scan(&scopes)
	return scopes, err
}

const getToken = `-- name: GetToken :one
SELECT character_id, access_token, refresh_token_enc, expires_at, scopes, issued_at FROM tokens WHERE character_id = ?
`

func (q *Queries) GetToken(ctx context.Context, characterID int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, characterID)
	var i Token
	err := row.Scan(
		&i.CharacterID,
		&i.AccessToken,
		&i.RefreshTokenEnc,
		&i.ExpiresAt,
		&i.Scopes,
		&i.IssuedAt,
	)
	return i, err
}

const upsertToken = `-- name: UpsertToken :exec
INSERT INTO tokens (character_id, access_token, refresh_token_enc, expires_at, scopes, issued_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token_enc = excluded.refresh_token_enc,
    expires_at = excluded.expires_at,
    scopes = excluded.scopes,
    issued_at = excluded.issued_at
`

type UpsertTokenParams struct {
	CharacterID     int64  `json:"characterId"`
	AccessToken     string `json:"accessToken"`
	RefreshTokenEnc []byte `json:"refreshTokenEnc"`
	ExpiresAt       int64  `json:"expiresAt"`
	Scopes          string `json:"scopes"`
	IssuedAt        int64  `json:"issuedAt"`
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertToken,
		arg.CharacterID,
		arg.AccessToken,
		arg.RefreshTokenEnc,
		arg.ExpiresAt,
		arg.Scopes,
		arg.IssuedAt,
	)
	return err
}
