// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package token

type Token struct {
	CharacterID     int64  `json:"characterId"`
	AccessToken     string `json:"accessToken"`
	RefreshTokenEnc []byte `json:"refreshTokenEnc"`
	ExpiresAt       int64  `json:"expiresAt"`
	Scopes          string `json:"scopes"`
	IssuedAt        int64  `json:"issuedAt"`
}
