// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Bonus {
    "bonus"?: number | null;
    "bonusText"?: Text | null;
    "importance"?: number | null;
    "unitID"?: number | null;

    /** Creates a new Bonus instance. */
    constructor($$source: Partial<Bonus> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bonus instance from a string or object.
     */
    static createFrom($$source: any = {}): Bonus {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bonusText" in $$parsedSource) {
            $$parsedSource["bonusText"] = $$createField1_0($$parsedSource["bonusText"]);
        }
        return new Bonus($$parsedSource as Partial<Bonus>);
    }
}

export class Certificate {
    "skillTypes": CertificateSkill[];

    /** Creates a new Certificate instance. */
    constructor($$source: Partial<Certificate> = {}) {
        if (!("skillTypes" in $$source)) {
            this["skillTypes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Certificate instance from a string or object.
     */
    static createFrom($$source: any = {}): Certificate {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skillTypes" in $$parsedSource) {
            $$parsedSource["skillTypes"] = $$createField0_0($$parsedSource["skillTypes"]);
        }
        return new Certificate($$parsedSource as Partial<Certificate>);
    }
}

export class CertificateSkill {
    "_key": number;
    "basic": number;
    "standard": number;
    "improved": number;
    "advanced": number;
    "elite": number;

    /** Creates a new CertificateSkill instance. */
    constructor($$source: Partial<CertificateSkill> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("basic" in $$source)) {
            this["basic"] = 0;
        }
        if (!("standard" in $$source)) {
            this["standard"] = 0;
        }
        if (!("improved" in $$source)) {
            this["improved"] = 0;
        }
        if (!("advanced" in $$source)) {
            this["advanced"] = 0;
        }
        if (!("elite" in $$source)) {
            this["elite"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertificateSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): CertificateSkill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CertificateSkill($$parsedSource as Partial<CertificateSkill>);
    }
}

export class CloneGrade {
    "skills": CloneGradeSkill[];

    /** Creates a new CloneGrade instance. */
    constructor($$source: Partial<CloneGrade> = {}) {
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneGrade instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneGrade {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField0_0($$parsedSource["skills"]);
        }
        return new CloneGrade($$parsedSource as Partial<CloneGrade>);
    }
}

export class CloneGradeSkill {
    "level": number;
    "typeID": number;

    /** Creates a new CloneGradeSkill instance. */
    constructor($$source: Partial<CloneGradeSkill> = {}) {
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("typeID" in $$source)) {
            this["typeID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneGradeSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneGradeSkill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloneGradeSkill($$parsedSource as Partial<CloneGradeSkill>);
    }
}

/**
 * Data is the subset of the package's Data tables the tree reads, in the same
 * shape as its JSONL files. Keys are SDE keys.
 */
export class Data {
    "types": { [_ in `${number}`]?: Type };
    "requiredSkills": { [_ in `${number}`]?: RequiredSkills };
    "certificates": { [_ in `${number}`]?: Certificate };
    "masteries": { [_ in `${number}`]?: Keyed[] };
    "cloneGrades": { [_ in `${number}`]?: CloneGrade };
    "shipTreeGroups": { [_ in `${number}`]?: ShipTreeGroup };
    "shipSizes": { [_ in `${number}`]?: ShipSize };

    /**
     * For the faction summary and tooltips; the tree itself does not read these.
     */
    "shipTreeFactions": { [_ in `${number}`]?: ShipTreeFaction };
    "shipTreeElements": { [_ in `${number}`]?: ShipTreeElement };
    "skills": { [_ in `${number}`]?: Skill };
    "typeBonus": { [_ in `${number}`]?: TypeBonus };
    "typeElements": { [_ in `${number}`]?: TypeElements };

    /** Creates a new Data instance. */
    constructor($$source: Partial<Data> = {}) {
        if (!("types" in $$source)) {
            this["types"] = {};
        }
        if (!("requiredSkills" in $$source)) {
            this["requiredSkills"] = {};
        }
        if (!("certificates" in $$source)) {
            this["certificates"] = {};
        }
        if (!("masteries" in $$source)) {
            this["masteries"] = {};
        }
        if (!("cloneGrades" in $$source)) {
            this["cloneGrades"] = {};
        }
        if (!("shipTreeGroups" in $$source)) {
            this["shipTreeGroups"] = {};
        }
        if (!("shipSizes" in $$source)) {
            this["shipSizes"] = {};
        }
        if (!("shipTreeFactions" in $$source)) {
            this["shipTreeFactions"] = {};
        }
        if (!("shipTreeElements" in $$source)) {
            this["shipTreeElements"] = {};
        }
        if (!("skills" in $$source)) {
            this["skills"] = {};
        }
        if (!("typeBonus" in $$source)) {
            this["typeBonus"] = {};
        }
        if (!("typeElements" in $$source)) {
            this["typeElements"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Data instance from a string or object.
     */
    static createFrom($$source: any = {}): Data {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType14;
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType18;
        const $$createField6_0 = $$createType20;
        const $$createField7_0 = $$createType22;
        const $$createField8_0 = $$createType24;
        const $$createField9_0 = $$createType26;
        const $$createField10_0 = $$createType28;
        const $$createField11_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField0_0($$parsedSource["types"]);
        }
        if ("requiredSkills" in $$parsedSource) {
            $$parsedSource["requiredSkills"] = $$createField1_0($$parsedSource["requiredSkills"]);
        }
        if ("certificates" in $$parsedSource) {
            $$parsedSource["certificates"] = $$createField2_0($$parsedSource["certificates"]);
        }
        if ("masteries" in $$parsedSource) {
            $$parsedSource["masteries"] = $$createField3_0($$parsedSource["masteries"]);
        }
        if ("cloneGrades" in $$parsedSource) {
            $$parsedSource["cloneGrades"] = $$createField4_0($$parsedSource["cloneGrades"]);
        }
        if ("shipTreeGroups" in $$parsedSource) {
            $$parsedSource["shipTreeGroups"] = $$createField5_0($$parsedSource["shipTreeGroups"]);
        }
        if ("shipSizes" in $$parsedSource) {
            $$parsedSource["shipSizes"] = $$createField6_0($$parsedSource["shipSizes"]);
        }
        if ("shipTreeFactions" in $$parsedSource) {
            $$parsedSource["shipTreeFactions"] = $$createField7_0($$parsedSource["shipTreeFactions"]);
        }
        if ("shipTreeElements" in $$parsedSource) {
            $$parsedSource["shipTreeElements"] = $$createField8_0($$parsedSource["shipTreeElements"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField9_0($$parsedSource["skills"]);
        }
        if ("typeBonus" in $$parsedSource) {
            $$parsedSource["typeBonus"] = $$createField10_0($$parsedSource["typeBonus"]);
        }
        if ("typeElements" in $$parsedSource) {
            $$parsedSource["typeElements"] = $$createField11_0($$parsedSource["typeElements"]);
        }
        return new Data($$parsedSource as Partial<Data>);
    }
}

export class Element {
    "_key": number;
    "_value": number;

    /** Creates a new Element instance. */
    constructor($$source: Partial<Element> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("_value" in $$source)) {
            this["_value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Element instance from a string or object.
     */
    static createFrom($$source: any = {}): Element {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Element($$parsedSource as Partial<Element>);
    }
}

export class GroupSkill {
    "_key": number;
    "display": boolean;
    "level": number;

    /** Creates a new GroupSkill instance. */
    constructor($$source: Partial<GroupSkill> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("display" in $$source)) {
            this["display"] = false;
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupSkill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupSkill($$parsedSource as Partial<GroupSkill>);
    }
}

/**
 * GroupSkills are the skills a group needs for one faction.
 */
export class GroupSkills {
    "_key": number;
    "skills": GroupSkill[];

    /** Creates a new GroupSkills instance. */
    constructor($$source: Partial<GroupSkills> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupSkills instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupSkills {
        const $$createField1_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField1_0($$parsedSource["skills"]);
        }
        return new GroupSkills($$parsedSource as Partial<GroupSkills>);
    }
}

/**
 * Keyed is a mastery level (0-4) and the certificates it needs.
 */
export class Keyed {
    "_key": number;
    "_value": number[];

    /** Creates a new Keyed instance. */
    constructor($$source: Partial<Keyed> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("_value" in $$source)) {
            this["_value"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keyed instance from a string or object.
     */
    static createFrom($$source: any = {}): Keyed {
        const $$createField1_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("_value" in $$parsedSource) {
            $$parsedSource["_value"] = $$createField1_0($$parsedSource["_value"]);
        }
        return new Keyed($$parsedSource as Partial<Keyed>);
    }
}

export class RequiredSkills {
    "requiredSkills": { [_ in `${number}`]?: number };

    /** Creates a new RequiredSkills instance. */
    constructor($$source: Partial<RequiredSkills> = {}) {
        if (!("requiredSkills" in $$source)) {
            this["requiredSkills"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequiredSkills instance from a string or object.
     */
    static createFrom($$source: any = {}): RequiredSkills {
        const $$createField0_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requiredSkills" in $$parsedSource) {
            $$parsedSource["requiredSkills"] = $$createField0_0($$parsedSource["requiredSkills"]);
        }
        return new RequiredSkills($$parsedSource as Partial<RequiredSkills>);
    }
}

export class ShipSize {
    "typeIDs": number[];

    /** Creates a new ShipSize instance. */
    constructor($$source: Partial<ShipSize> = {}) {
        if (!("typeIDs" in $$source)) {
            this["typeIDs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShipSize instance from a string or object.
     */
    static createFrom($$source: any = {}): ShipSize {
        const $$createField0_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("typeIDs" in $$parsedSource) {
            $$parsedSource["typeIDs"] = $$createField0_0($$parsedSource["typeIDs"]);
        }
        return new ShipSize($$parsedSource as Partial<ShipSize>);
    }
}

/**
 * ShipTreeElement is a trait a faction or group excels at, like Armor or Drones.
 */
export class ShipTreeElement {
    "name"?: Text | null;
    "description"?: Text | null;

    /** Creates a new ShipTreeElement instance. */
    constructor($$source: Partial<ShipTreeElement> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShipTreeElement instance from a string or object.
     */
    static createFrom($$source: any = {}): ShipTreeElement {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField0_0($$parsedSource["name"]);
        }
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField1_0($$parsedSource["description"]);
        }
        return new ShipTreeElement($$parsedSource as Partial<ShipTreeElement>);
    }
}

/**
 * ShipTreeFaction is a faction's summary: what it excels at and how it fights.
 */
export class ShipTreeFaction {
    "description"?: Text | null;
    "elements": Element[];

    /** Creates a new ShipTreeFaction instance. */
    constructor($$source: Partial<ShipTreeFaction> = {}) {
        if (!("elements" in $$source)) {
            this["elements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShipTreeFaction instance from a string or object.
     */
    static createFrom($$source: any = {}): ShipTreeFaction {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField0_0($$parsedSource["description"]);
        }
        if ("elements" in $$parsedSource) {
            $$parsedSource["elements"] = $$createField1_0($$parsedSource["elements"]);
        }
        return new ShipTreeFaction($$parsedSource as Partial<ShipTreeFaction>);
    }
}

export class ShipTreeGroup {
    "name"?: Text | null;
    "description"?: Text | null;
    "elements": Element[];
    "preReqSkills": GroupSkills[];

    /** Creates a new ShipTreeGroup instance. */
    constructor($$source: Partial<ShipTreeGroup> = {}) {
        if (!("elements" in $$source)) {
            this["elements"] = [];
        }
        if (!("preReqSkills" in $$source)) {
            this["preReqSkills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShipTreeGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ShipTreeGroup {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType36;
        const $$createField3_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField0_0($$parsedSource["name"]);
        }
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField1_0($$parsedSource["description"]);
        }
        if ("elements" in $$parsedSource) {
            $$parsedSource["elements"] = $$createField2_0($$parsedSource["elements"]);
        }
        if ("preReqSkills" in $$parsedSource) {
            $$parsedSource["preReqSkills"] = $$createField3_0($$parsedSource["preReqSkills"]);
        }
        return new ShipTreeGroup($$parsedSource as Partial<ShipTreeGroup>);
    }
}

/**
 * Skill is a skill the ships require, named in tooltips.
 */
export class Skill {
    "name"?: Text | null;

    /** Creates a new Skill instance. */
    constructor($$source: Partial<Skill> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     */
    static createFrom($$source: any = {}): Skill {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField0_0($$parsedSource["name"]);
        }
        return new Skill($$parsedSource as Partial<Skill>);
    }
}

export class SkillBonuses {
    "_key": number;
    "_value": Bonus[];

    /** Creates a new SkillBonuses instance. */
    constructor($$source: Partial<SkillBonuses> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("_value" in $$source)) {
            this["_value"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillBonuses instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillBonuses {
        const $$createField1_0 = $$createType40;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("_value" in $$parsedSource) {
            $$parsedSource["_value"] = $$createField1_0($$parsedSource["_value"]);
        }
        return new SkillBonuses($$parsedSource as Partial<SkillBonuses>);
    }
}

/**
 * Text is a localized SDE string. Only English is built.
 */
export class Text {
    "en": string;

    /** Creates a new Text instance. */
    constructor($$source: Partial<Text> = {}) {
        if (!("en" in $$source)) {
            this["en"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Text instance from a string or object.
     */
    static createFrom($$source: any = {}): Text {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Text($$parsedSource as Partial<Text>);
    }
}

export class Type {
    "name"?: Text | null;
    "shipTreeGroupID"?: number | null;
    "factionID"?: number | null;
    "metaGroupID"?: number | null;
    "techLevel": number;

    /** Creates a new Type instance. */
    constructor($$source: Partial<Type> = {}) {
        if (!("techLevel" in $$source)) {
            this["techLevel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Type instance from a string or object.
     */
    static createFrom($$source: any = {}): Type {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField0_0($$parsedSource["name"]);
        }
        return new Type($$parsedSource as Partial<Type>);
    }
}

/**
 * TypeBonus holds a ship's bonuses: per level of the skill in Types[].Key, role and misc.
 */
export class TypeBonus {
    "types"?: SkillBonuses[];
    "roleBonuses"?: Bonus[];
    "miscBonuses"?: Bonus[];

    /** Creates a new TypeBonus instance. */
    constructor($$source: Partial<TypeBonus> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeBonus instance from a string or object.
     */
    static createFrom($$source: any = {}): TypeBonus {
        const $$createField0_0 = $$createType42;
        const $$createField1_0 = $$createType40;
        const $$createField2_0 = $$createType40;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField0_0($$parsedSource["types"]);
        }
        if ("roleBonuses" in $$parsedSource) {
            $$parsedSource["roleBonuses"] = $$createField1_0($$parsedSource["roleBonuses"]);
        }
        if ("miscBonuses" in $$parsedSource) {
            $$parsedSource["miscBonuses"] = $$createField2_0($$parsedSource["miscBonuses"]);
        }
        return new TypeBonus($$parsedSource as Partial<TypeBonus>);
    }
}

/**
 * TypeElements are the traits shown on a ship's tooltip, size first.
 */
export class TypeElements {
    "elements": Element[];

    /** Creates a new TypeElements instance. */
    constructor($$source: Partial<TypeElements> = {}) {
        if (!("elements" in $$source)) {
            this["elements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeElements instance from a string or object.
     */
    static createFrom($$source: any = {}): TypeElements {
        const $$createField0_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("elements" in $$parsedSource) {
            $$parsedSource["elements"] = $$createField0_0($$parsedSource["elements"]);
        }
        return new TypeElements($$parsedSource as Partial<TypeElements>);
    }
}

// Private type creation functions
const $$createType0 = Text.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = CertificateSkill.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = CloneGradeSkill.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Type.createFrom;
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = RequiredSkills.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = Certificate.createFrom;
const $$createType11 = $Create.Map($Create.Any, $$createType10);
const $$createType12 = Keyed.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = CloneGrade.createFrom;
const $$createType16 = $Create.Map($Create.Any, $$createType15);
const $$createType17 = ShipTreeGroup.createFrom;
const $$createType18 = $Create.Map($Create.Any, $$createType17);
const $$createType19 = ShipSize.createFrom;
const $$createType20 = $Create.Map($Create.Any, $$createType19);
const $$createType21 = ShipTreeFaction.createFrom;
const $$createType22 = $Create.Map($Create.Any, $$createType21);
const $$createType23 = ShipTreeElement.createFrom;
const $$createType24 = $Create.Map($Create.Any, $$createType23);
const $$createType25 = Skill.createFrom;
const $$createType26 = $Create.Map($Create.Any, $$createType25);
const $$createType27 = TypeBonus.createFrom;
const $$createType28 = $Create.Map($Create.Any, $$createType27);
const $$createType29 = TypeElements.createFrom;
const $$createType30 = $Create.Map($Create.Any, $$createType29);
const $$createType31 = GroupSkill.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $Create.Array($Create.Any);
const $$createType34 = $Create.Map($Create.Any, $Create.Any);
const $$createType35 = Element.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = GroupSkills.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = Bonus.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = SkillBonuses.createFrom;
const $$createType42 = $Create.Array($$createType41);
