// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Certificate {
    "skillTypes": CertificateSkill[];

    /** Creates a new Certificate instance. */
    constructor($$source: Partial<Certificate> = {}) {
        if (!("skillTypes" in $$source)) {
            this["skillTypes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Certificate instance from a string or object.
     */
    static createFrom($$source: any = {}): Certificate {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skillTypes" in $$parsedSource) {
            $$parsedSource["skillTypes"] = $$createField0_0($$parsedSource["skillTypes"]);
        }
        return new Certificate($$parsedSource as Partial<Certificate>);
    }
}

export class CertificateSkill {
    "_key": number;
    "basic": number;
    "standard": number;
    "improved": number;
    "advanced": number;
    "elite": number;

    /** Creates a new CertificateSkill instance. */
    constructor($$source: Partial<CertificateSkill> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("basic" in $$source)) {
            this["basic"] = 0;
        }
        if (!("standard" in $$source)) {
            this["standard"] = 0;
        }
        if (!("improved" in $$source)) {
            this["improved"] = 0;
        }
        if (!("advanced" in $$source)) {
            this["advanced"] = 0;
        }
        if (!("elite" in $$source)) {
            this["elite"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertificateSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): CertificateSkill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CertificateSkill($$parsedSource as Partial<CertificateSkill>);
    }
}

export class CloneGrade {
    "skills": CloneGradeSkill[];

    /** Creates a new CloneGrade instance. */
    constructor($$source: Partial<CloneGrade> = {}) {
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneGrade instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneGrade {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField0_0($$parsedSource["skills"]);
        }
        return new CloneGrade($$parsedSource as Partial<CloneGrade>);
    }
}

export class CloneGradeSkill {
    "level": number;
    "typeID": number;

    /** Creates a new CloneGradeSkill instance. */
    constructor($$source: Partial<CloneGradeSkill> = {}) {
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("typeID" in $$source)) {
            this["typeID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneGradeSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneGradeSkill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloneGradeSkill($$parsedSource as Partial<CloneGradeSkill>);
    }
}

/**
 * Data is the subset of the package's Data tables the tree reads, in the same
 * shape as its JSONL files. Keys are SDE keys.
 */
export class Data {
    "types": { [_ in `${number}`]?: Type };
    "requiredSkills": { [_ in `${number}`]?: RequiredSkills };
    "certificates": { [_ in `${number}`]?: Certificate };
    "masteries": { [_ in `${number}`]?: Keyed[] };
    "cloneGrades": { [_ in `${number}`]?: CloneGrade };
    "shipTreeGroups": { [_ in `${number}`]?: ShipTreeGroup };
    "shipSizes": { [_ in `${number}`]?: ShipSize };

    /** Creates a new Data instance. */
    constructor($$source: Partial<Data> = {}) {
        if (!("types" in $$source)) {
            this["types"] = {};
        }
        if (!("requiredSkills" in $$source)) {
            this["requiredSkills"] = {};
        }
        if (!("certificates" in $$source)) {
            this["certificates"] = {};
        }
        if (!("masteries" in $$source)) {
            this["masteries"] = {};
        }
        if (!("cloneGrades" in $$source)) {
            this["cloneGrades"] = {};
        }
        if (!("shipTreeGroups" in $$source)) {
            this["shipTreeGroups"] = {};
        }
        if (!("shipSizes" in $$source)) {
            this["shipSizes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Data instance from a string or object.
     */
    static createFrom($$source: any = {}): Data {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType14;
        const $$createField5_0 = $$createType16;
        const $$createField6_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField0_0($$parsedSource["types"]);
        }
        if ("requiredSkills" in $$parsedSource) {
            $$parsedSource["requiredSkills"] = $$createField1_0($$parsedSource["requiredSkills"]);
        }
        if ("certificates" in $$parsedSource) {
            $$parsedSource["certificates"] = $$createField2_0($$parsedSource["certificates"]);
        }
        if ("masteries" in $$parsedSource) {
            $$parsedSource["masteries"] = $$createField3_0($$parsedSource["masteries"]);
        }
        if ("cloneGrades" in $$parsedSource) {
            $$parsedSource["cloneGrades"] = $$createField4_0($$parsedSource["cloneGrades"]);
        }
        if ("shipTreeGroups" in $$parsedSource) {
            $$parsedSource["shipTreeGroups"] = $$createField5_0($$parsedSource["shipTreeGroups"]);
        }
        if ("shipSizes" in $$parsedSource) {
            $$parsedSource["shipSizes"] = $$createField6_0($$parsedSource["shipSizes"]);
        }
        return new Data($$parsedSource as Partial<Data>);
    }
}

export class Element {
    "_key": number;
    "_value": number;

    /** Creates a new Element instance. */
    constructor($$source: Partial<Element> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("_value" in $$source)) {
            this["_value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Element instance from a string or object.
     */
    static createFrom($$source: any = {}): Element {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Element($$parsedSource as Partial<Element>);
    }
}

export class GroupSkill {
    "_key": number;
    "display": boolean;
    "level": number;

    /** Creates a new GroupSkill instance. */
    constructor($$source: Partial<GroupSkill> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("display" in $$source)) {
            this["display"] = false;
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupSkill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupSkill($$parsedSource as Partial<GroupSkill>);
    }
}

/**
 * GroupSkills are the skills a group needs for one faction.
 */
export class GroupSkills {
    "_key": number;
    "skills": GroupSkill[];

    /** Creates a new GroupSkills instance. */
    constructor($$source: Partial<GroupSkills> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupSkills instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupSkills {
        const $$createField1_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField1_0($$parsedSource["skills"]);
        }
        return new GroupSkills($$parsedSource as Partial<GroupSkills>);
    }
}

/**
 * Keyed is a mastery level (0-4) and the certificates it needs.
 */
export class Keyed {
    "_key": number;
    "_value": number[];

    /** Creates a new Keyed instance. */
    constructor($$source: Partial<Keyed> = {}) {
        if (!("_key" in $$source)) {
            this["_key"] = 0;
        }
        if (!("_value" in $$source)) {
            this["_value"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keyed instance from a string or object.
     */
    static createFrom($$source: any = {}): Keyed {
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("_value" in $$parsedSource) {
            $$parsedSource["_value"] = $$createField1_0($$parsedSource["_value"]);
        }
        return new Keyed($$parsedSource as Partial<Keyed>);
    }
}

export class RequiredSkills {
    "requiredSkills": { [_ in `${number}`]?: number };

    /** Creates a new RequiredSkills instance. */
    constructor($$source: Partial<RequiredSkills> = {}) {
        if (!("requiredSkills" in $$source)) {
            this["requiredSkills"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequiredSkills instance from a string or object.
     */
    static createFrom($$source: any = {}): RequiredSkills {
        const $$createField0_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requiredSkills" in $$parsedSource) {
            $$parsedSource["requiredSkills"] = $$createField0_0($$parsedSource["requiredSkills"]);
        }
        return new RequiredSkills($$parsedSource as Partial<RequiredSkills>);
    }
}

export class ShipSize {
    "typeIDs": number[];

    /** Creates a new ShipSize instance. */
    constructor($$source: Partial<ShipSize> = {}) {
        if (!("typeIDs" in $$source)) {
            this["typeIDs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShipSize instance from a string or object.
     */
    static createFrom($$source: any = {}): ShipSize {
        const $$createField0_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("typeIDs" in $$parsedSource) {
            $$parsedSource["typeIDs"] = $$createField0_0($$parsedSource["typeIDs"]);
        }
        return new ShipSize($$parsedSource as Partial<ShipSize>);
    }
}

export class ShipTreeGroup {
    "elements": Element[];
    "preReqSkills": GroupSkills[];

    /** Creates a new ShipTreeGroup instance. */
    constructor($$source: Partial<ShipTreeGroup> = {}) {
        if (!("elements" in $$source)) {
            this["elements"] = [];
        }
        if (!("preReqSkills" in $$source)) {
            this["preReqSkills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShipTreeGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ShipTreeGroup {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("elements" in $$parsedSource) {
            $$parsedSource["elements"] = $$createField0_0($$parsedSource["elements"]);
        }
        if ("preReqSkills" in $$parsedSource) {
            $$parsedSource["preReqSkills"] = $$createField1_0($$parsedSource["preReqSkills"]);
        }
        return new ShipTreeGroup($$parsedSource as Partial<ShipTreeGroup>);
    }
}

export class Type {
    "shipTreeGroupID"?: number | null;
    "factionID"?: number | null;
    "metaGroupID"?: number | null;
    "techLevel": number;

    /** Creates a new Type instance. */
    constructor($$source: Partial<Type> = {}) {
        if (!("techLevel" in $$source)) {
            this["techLevel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Type instance from a string or object.
     */
    static createFrom($$source: any = {}): Type {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Type($$parsedSource as Partial<Type>);
    }
}

// Private type creation functions
const $$createType0 = CertificateSkill.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CloneGradeSkill.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Type.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = RequiredSkills.createFrom;
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = Certificate.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = Keyed.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = CloneGrade.createFrom;
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = ShipTreeGroup.createFrom;
const $$createType16 = $Create.Map($Create.Any, $$createType15);
const $$createType17 = ShipSize.createFrom;
const $$createType18 = $Create.Map($Create.Any, $$createType17);
const $$createType19 = GroupSkill.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Array($Create.Any);
const $$createType22 = $Create.Map($Create.Any, $Create.Any);
const $$createType23 = Element.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = GroupSkills.createFrom;
const $$createType26 = $Create.Array($$createType25);
