// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing side of the ship tree data.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Data returns the tree's static data, built once per installed SDE. It fails
 * before the first install; the frontend refetches on sde:changed.
 */
export function Data(): $CancellablePromise<$models.Data | null> {
    return $Call.ByID(1257128812).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Data.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
