// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package charactersheet

import (
	"context"
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/alliance"
	"github.com/eve-online-tools/lib-esi-go/common/bloodline"
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/faction"
	"github.com/eve-online-tools/lib-esi-go/common/race"
	"github.com/eve-online-tools/lib-esi-go/common/station"
)

const getAlliance = `-- name: GetAlliance :one
SELECT id, name, ticker, creator_id, creator_corporation_id, executor_corporation_id, faction_id, date_founded, fetched_at FROM alliances WHERE id = ?
`

func (q *Queries) GetAlliance(ctx context.Context, id alliance.Identifier) (Alliance, error) {
	row := q.db.QueryRowContext(ctx, getAlliance, id)
	var i Alliance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ticker,
		&i.CreatorID,
		&i.CreatorCorporationID,
		&i.ExecutorCorporationID,
		&i.FactionID,
		&i.DateFounded,
		&i.FetchedAt,
	)
	return i, err
}

const getCharacter = `-- name: GetCharacter :one
SELECT character_id, corporation_id, alliance_id, faction_id, birthday, bloodline_id, race_id, gender, security_status, title, description, fetched_at FROM character_sheets WHERE character_id = ?
`

func (q *Queries) GetCharacter(ctx context.Context, characterID int64) (CharacterSheet, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, characterID)
	var i CharacterSheet
	err := row.Scan(
		&i.CharacterID,
		&i.CorporationID,
		&i.AllianceID,
		&i.FactionID,
		&i.Birthday,
		&i.BloodlineID,
		&i.RaceID,
		&i.Gender,
		&i.SecurityStatus,
		&i.Title,
		&i.Description,
		&i.FetchedAt,
	)
	return i, err
}

const getCorporation = `-- name: GetCorporation :one
SELECT id, name, ticker, alliance_id, ceo_id, creator_id, enlisted_faction_id, home_station_id, date_founded, member_count, tax_rate, war_eligible, url, description, fetched_at FROM corporations WHERE id = ?
`

func (q *Queries) GetCorporation(ctx context.Context, id corporation.Identifier) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, getCorporation, id)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ticker,
		&i.AllianceID,
		&i.CeoID,
		&i.CreatorID,
		&i.EnlistedFactionID,
		&i.HomeStationID,
		&i.DateFounded,
		&i.MemberCount,
		&i.TaxRate,
		&i.WarEligible,
		&i.Url,
		&i.Description,
		&i.FetchedAt,
	)
	return i, err
}

const upsertAlliance = `-- name: UpsertAlliance :exec
INSERT INTO alliances (id, name, ticker, creator_id, creator_corporation_id, executor_corporation_id,
    faction_id, date_founded, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    ticker = excluded.ticker,
    creator_id = excluded.creator_id,
    creator_corporation_id = excluded.creator_corporation_id,
    executor_corporation_id = excluded.executor_corporation_id,
    faction_id = excluded.faction_id,
    date_founded = excluded.date_founded,
    fetched_at = excluded.fetched_at
`

type UpsertAllianceParams struct {
	ID                    alliance.Identifier     `json:"id"`
	Name                  string                  `json:"name"`
	Ticker                string                  `json:"ticker"`
	CreatorID             character.Identifier    `json:"creatorId"`
	CreatorCorporationID  corporation.Identifier  `json:"creatorCorporationId"`
	ExecutorCorporationID *corporation.Identifier `json:"executorCorporationId"`
	FactionID             *faction.Identifier     `json:"factionId"`
	DateFounded           time.Time               `json:"dateFounded"`
	FetchedAt             time.Time               `json:"fetchedAt"`
}

func (q *Queries) UpsertAlliance(ctx context.Context, arg UpsertAllianceParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlliance,
		arg.ID,
		arg.Name,
		arg.Ticker,
		arg.CreatorID,
		arg.CreatorCorporationID,
		arg.ExecutorCorporationID,
		arg.FactionID,
		arg.DateFounded,
		arg.FetchedAt,
	)
	return err
}

const upsertCharacter = `-- name: UpsertCharacter :exec
INSERT INTO character_sheets (character_id, corporation_id, alliance_id, faction_id, birthday, bloodline_id,
    race_id, gender, security_status, title, description, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    corporation_id = excluded.corporation_id,
    alliance_id = excluded.alliance_id,
    faction_id = excluded.faction_id,
    birthday = excluded.birthday,
    bloodline_id = excluded.bloodline_id,
    race_id = excluded.race_id,
    gender = excluded.gender,
    security_status = excluded.security_status,
    title = excluded.title,
    description = excluded.description,
    fetched_at = excluded.fetched_at
`

type UpsertCharacterParams struct {
	CharacterID    int64                  `json:"characterId"`
	CorporationID  corporation.Identifier `json:"corporationId"`
	AllianceID     *alliance.Identifier   `json:"allianceId"`
	FactionID      *faction.Identifier    `json:"factionId"`
	Birthday       time.Time              `json:"birthday"`
	BloodlineID    bloodline.Identifier   `json:"bloodlineId"`
	RaceID         race.Identifier        `json:"raceId"`
	Gender         string                 `json:"gender"`
	SecurityStatus *float64               `json:"securityStatus"`
	Title          *string                `json:"title"`
	Description    *string                `json:"description"`
	FetchedAt      time.Time              `json:"fetchedAt"`
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacter,
		arg.CharacterID,
		arg.CorporationID,
		arg.AllianceID,
		arg.FactionID,
		arg.Birthday,
		arg.BloodlineID,
		arg.RaceID,
		arg.Gender,
		arg.SecurityStatus,
		arg.Title,
		arg.Description,
		arg.FetchedAt,
	)
	return err
}

const upsertCorporation = `-- name: UpsertCorporation :exec
INSERT INTO corporations (id, name, ticker, alliance_id, ceo_id, creator_id, enlisted_faction_id, home_station_id,
    date_founded, member_count, tax_rate, war_eligible, url, description, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    ticker = excluded.ticker,
    alliance_id = excluded.alliance_id,
    ceo_id = excluded.ceo_id,
    creator_id = excluded.creator_id,
    enlisted_faction_id = excluded.enlisted_faction_id,
    home_station_id = excluded.home_station_id,
    date_founded = excluded.date_founded,
    member_count = excluded.member_count,
    tax_rate = excluded.tax_rate,
    war_eligible = excluded.war_eligible,
    url = excluded.url,
    description = excluded.description,
    fetched_at = excluded.fetched_at
`

type UpsertCorporationParams struct {
	ID                corporation.Identifier `json:"id"`
	Name              string                 `json:"name"`
	Ticker            string                 `json:"ticker"`
	AllianceID        *alliance.Identifier   `json:"allianceId"`
	CeoID             *character.Identifier  `json:"ceoId"`
	CreatorID         *character.Identifier  `json:"creatorId"`
	EnlistedFactionID *faction.Identifier    `json:"enlistedFactionId"`
	HomeStationID     station.Identifier     `json:"homeStationId"`
	DateFounded       *time.Time             `json:"dateFounded"`
	MemberCount       int64                  `json:"memberCount"`
	TaxRate           float64                `json:"taxRate"`
	WarEligible       bool                   `json:"warEligible"`
	Url               *string                `json:"url"`
	Description       string                 `json:"description"`
	FetchedAt         time.Time              `json:"fetchedAt"`
}

func (q *Queries) UpsertCorporation(ctx context.Context, arg UpsertCorporationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCorporation,
		arg.ID,
		arg.Name,
		arg.Ticker,
		arg.AllianceID,
		arg.CeoID,
		arg.CreatorID,
		arg.EnlistedFactionID,
		arg.HomeStationID,
		arg.DateFounded,
		arg.MemberCount,
		arg.TaxRate,
		arg.WarEligible,
		arg.Url,
		arg.Description,
		arg.FetchedAt,
	)
	return err
}
