// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package charactersheet

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/alliance"
	"github.com/eve-online-tools/lib-esi-go/common/bloodline"
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/faction"
	"github.com/eve-online-tools/lib-esi-go/common/race"
	"github.com/eve-online-tools/lib-esi-go/common/station"
)

type Alliance struct {
	ID                    alliance.Identifier     `json:"id"`
	Name                  string                  `json:"name"`
	Ticker                string                  `json:"ticker"`
	CreatorID             character.Identifier    `json:"creatorId"`
	CreatorCorporationID  corporation.Identifier  `json:"creatorCorporationId"`
	ExecutorCorporationID *corporation.Identifier `json:"executorCorporationId"`
	FactionID             *faction.Identifier     `json:"factionId"`
	DateFounded           time.Time               `json:"dateFounded"`
	FetchedAt             time.Time               `json:"fetchedAt"`
}

type CharacterSheet struct {
	CharacterID    int64                  `json:"characterId"`
	CorporationID  corporation.Identifier `json:"corporationId"`
	AllianceID     *alliance.Identifier   `json:"allianceId"`
	FactionID      *faction.Identifier    `json:"factionId"`
	Birthday       time.Time              `json:"birthday"`
	BloodlineID    bloodline.Identifier   `json:"bloodlineId"`
	RaceID         race.Identifier        `json:"raceId"`
	Gender         string                 `json:"gender"`
	SecurityStatus *float64               `json:"securityStatus"`
	Title          *string                `json:"title"`
	Description    *string                `json:"description"`
	FetchedAt      time.Time              `json:"fetchedAt"`
}

type Corporation struct {
	ID                corporation.Identifier `json:"id"`
	Name              string                 `json:"name"`
	Ticker            string                 `json:"ticker"`
	AllianceID        *alliance.Identifier   `json:"allianceId"`
	CeoID             *character.Identifier  `json:"ceoId"`
	CreatorID         *character.Identifier  `json:"creatorId"`
	EnlistedFactionID *faction.Identifier    `json:"enlistedFactionId"`
	HomeStationID     station.Identifier     `json:"homeStationId"`
	DateFounded       *time.Time             `json:"dateFounded"`
	MemberCount       int64                  `json:"memberCount"`
	TaxRate           float64                `json:"taxRate"`
	WarEligible       bool                   `json:"warEligible"`
	Url               *string                `json:"url"`
	Description       string                 `json:"description"`
	FetchedAt         time.Time              `json:"fetchedAt"`
}
