// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SetupStatus is what the welcome screen and checklist need to start a login.
 */
export class SetupStatus {
    "issuer": string;
    "loginUrl": string;

    /** Creates a new SetupStatus instance. */
    constructor($$source: Partial<SetupStatus> = {}) {
        if (!("issuer" in $$source)) {
            this["issuer"] = "";
        }
        if (!("loginUrl" in $$source)) {
            this["loginUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupStatus($$parsedSource as Partial<SetupStatus>);
    }
}
