// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProgressService gives a UI that opens mid-run the current progress of a key.
 * After that it follows the progress events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../core/task/models.js";

/**
 * Get returns the progress of the running task with the WithProgress key, nil
 * when it is not running.
 */
export function Get(key: string): $CancellablePromise<task$0.Progress | null> {
    return $Call.ByID(2016728319, key).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = task$0.Progress.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
