// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as solarsystem$0 from "../../../lib-esi-go/common/solarsystem/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typeid$0 from "../../../lib-esi-go/common/typeid/models.js";

export class ListPresenceRow {
    "characterId": number;
    "solarSystemId": solarsystem$0.Identifier;
    "online": boolean | null;
    "shipTypeId": typeid$0.Identifier | null;
    "shipName": string | null;

    /** Creates a new ListPresenceRow instance. */
    constructor($$source: Partial<ListPresenceRow> = {}) {
        if (!("characterId" in $$source)) {
            this["characterId"] = 0;
        }
        if (!("solarSystemId" in $$source)) {
            this["solarSystemId"] = 0;
        }
        if (!("online" in $$source)) {
            this["online"] = null;
        }
        if (!("shipTypeId" in $$source)) {
            this["shipTypeId"] = null;
        }
        if (!("shipName" in $$source)) {
            this["shipName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListPresenceRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ListPresenceRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListPresenceRow($$parsedSource as Partial<ListPresenceRow>);
    }
}
