// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing side of the feature.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns the last known location of every character that has one. The
 * frontend filters by scopes, so a character needing login keeps its last spot.
 */
export function List(): $CancellablePromise<$models.ListPresenceRow[]> {
    return $Call.ByID(3468371781).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ListPresenceRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
