// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

/**
 * Status is what the UI shows about static data.
 */
export class Status {
    /**
     * Build and ReleaseDate are zero before the first install.
     */
    "build": number;
    "releaseDate": string;

    /**
     * Latest is the build the last check saw, 0 before it.
     */
    "latest": number;
    "lastCheck": string;
    "updating": boolean;
    "progress": task$0.Progress | null;

    /**
     * LastError is the error of the last failed check or update.
     */
    "lastError": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("build" in $$source)) {
            this["build"] = 0;
        }
        if (!("releaseDate" in $$source)) {
            this["releaseDate"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("latest" in $$source)) {
            this["latest"] = 0;
        }
        if (!("lastCheck" in $$source)) {
            this["lastCheck"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updating" in $$source)) {
            this["updating"] = false;
        }
        if (!("progress" in $$source)) {
            this["progress"] = null;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("progress" in $$parsedSource) {
            $$parsedSource["progress"] = $$createField5_0($$parsedSource["progress"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = task$0.Progress.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
