// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package presence

import (
	"context"
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
	"github.com/eve-online-tools/lib-esi-go/common/station"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

const getLocation = `-- name: GetLocation :one
SELECT character_id, solar_system_id, station_id, structure_id, fetched_at FROM presence_locations WHERE character_id = ?
`

func (q *Queries) GetLocation(ctx context.Context, characterID int64) (PresenceLocation, error) {
	row := q.db.QueryRowContext(ctx, getLocation, characterID)
	var i PresenceLocation
	err := row.Scan(
		&i.CharacterID,
		&i.SolarSystemID,
		&i.StationID,
		&i.StructureID,
		&i.FetchedAt,
	)
	return i, err
}

const getOnline = `-- name: GetOnline :one
SELECT character_id, online, last_login, last_logout, logins, fetched_at FROM presence_online WHERE character_id = ?
`

func (q *Queries) GetOnline(ctx context.Context, characterID int64) (PresenceOnline, error) {
	row := q.db.QueryRowContext(ctx, getOnline, characterID)
	var i PresenceOnline
	err := row.Scan(
		&i.CharacterID,
		&i.Online,
		&i.LastLogin,
		&i.LastLogout,
		&i.Logins,
		&i.FetchedAt,
	)
	return i, err
}

const getShip = `-- name: GetShip :one
SELECT character_id, ship_item_id, ship_type_id, ship_name, fetched_at FROM presence_ships WHERE character_id = ?
`

func (q *Queries) GetShip(ctx context.Context, characterID int64) (PresenceShip, error) {
	row := q.db.QueryRowContext(ctx, getShip, characterID)
	var i PresenceShip
	err := row.Scan(
		&i.CharacterID,
		&i.ShipItemID,
		&i.ShipTypeID,
		&i.ShipName,
		&i.FetchedAt,
	)
	return i, err
}

const listOnline = `-- name: ListOnline :many
SELECT character_id, online, last_login, last_logout, logins, fetched_at FROM presence_online
`

func (q *Queries) ListOnline(ctx context.Context) ([]PresenceOnline, error) {
	rows, err := q.db.QueryContext(ctx, listOnline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PresenceOnline
	for rows.Next() {
		var i PresenceOnline
		if err := rows.Scan(
			&i.CharacterID,
			&i.Online,
			&i.LastLogin,
			&i.LastLogout,
			&i.Logins,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresence = `-- name: ListPresence :many
SELECT l.character_id, l.solar_system_id, o.online, s.ship_type_id, s.ship_name
FROM presence_locations l
LEFT JOIN presence_online o ON o.character_id = l.character_id
LEFT JOIN presence_ships s ON s.character_id = l.character_id
`

type ListPresenceRow struct {
	CharacterID   int64                  `json:"characterId"`
	SolarSystemID solarsystem.Identifier `json:"solarSystemId"`
	Online        *bool                  `json:"online"`
	ShipTypeID    *typeid.Identifier     `json:"shipTypeId"`
	ShipName      *string                `json:"shipName"`
}

func (q *Queries) ListPresence(ctx context.Context) ([]ListPresenceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPresence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPresenceRow
	for rows.Next() {
		var i ListPresenceRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.SolarSystemID,
			&i.Online,
			&i.ShipTypeID,
			&i.ShipName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocation = `-- name: UpsertLocation :one
INSERT INTO presence_locations (character_id, solar_system_id, station_id, structure_id, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    solar_system_id = excluded.solar_system_id,
    station_id = excluded.station_id,
    structure_id = excluded.structure_id,
    fetched_at = excluded.fetched_at
RETURNING character_id, solar_system_id, station_id, structure_id, fetched_at
`

type UpsertLocationParams struct {
	CharacterID   int64                  `json:"characterId"`
	SolarSystemID solarsystem.Identifier `json:"solarSystemId"`
	StationID     *station.Identifier    `json:"stationId"`
	StructureID   *item.Identifier       `json:"structureId"`
	FetchedAt     time.Time              `json:"fetchedAt"`
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) (PresenceLocation, error) {
	row := q.db.QueryRowContext(ctx, upsertLocation,
		arg.CharacterID,
		arg.SolarSystemID,
		arg.StationID,
		arg.StructureID,
		arg.FetchedAt,
	)
	var i PresenceLocation
	err := row.Scan(
		&i.CharacterID,
		&i.SolarSystemID,
		&i.StationID,
		&i.StructureID,
		&i.FetchedAt,
	)
	return i, err
}

const upsertOnline = `-- name: UpsertOnline :one
INSERT INTO presence_online (character_id, online, last_login, last_logout, logins, fetched_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    online = excluded.online,
    last_login = excluded.last_login,
    last_logout = excluded.last_logout,
    logins = excluded.logins,
    fetched_at = excluded.fetched_at
RETURNING character_id, online, last_login, last_logout, logins, fetched_at
`

type UpsertOnlineParams struct {
	CharacterID int64      `json:"characterId"`
	Online      bool       `json:"online"`
	LastLogin   *time.Time `json:"lastLogin"`
	LastLogout  *time.Time `json:"lastLogout"`
	Logins      *int64     `json:"logins"`
	FetchedAt   time.Time  `json:"fetchedAt"`
}

func (q *Queries) UpsertOnline(ctx context.Context, arg UpsertOnlineParams) (PresenceOnline, error) {
	row := q.db.QueryRowContext(ctx, upsertOnline,
		arg.CharacterID,
		arg.Online,
		arg.LastLogin,
		arg.LastLogout,
		arg.Logins,
		arg.FetchedAt,
	)
	var i PresenceOnline
	err := row.Scan(
		&i.CharacterID,
		&i.Online,
		&i.LastLogin,
		&i.LastLogout,
		&i.Logins,
		&i.FetchedAt,
	)
	return i, err
}

const upsertShip = `-- name: UpsertShip :one
INSERT INTO presence_ships (character_id, ship_item_id, ship_type_id, ship_name, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    ship_item_id = excluded.ship_item_id,
    ship_type_id = excluded.ship_type_id,
    ship_name = excluded.ship_name,
    fetched_at = excluded.fetched_at
RETURNING character_id, ship_item_id, ship_type_id, ship_name, fetched_at
`

type UpsertShipParams struct {
	CharacterID int64             `json:"characterId"`
	ShipItemID  item.Identifier   `json:"shipItemId"`
	ShipTypeID  typeid.Identifier `json:"shipTypeId"`
	ShipName    string            `json:"shipName"`
	FetchedAt   time.Time         `json:"fetchedAt"`
}

func (q *Queries) UpsertShip(ctx context.Context, arg UpsertShipParams) (PresenceShip, error) {
	row := q.db.QueryRowContext(ctx, upsertShip,
		arg.CharacterID,
		arg.ShipItemID,
		arg.ShipTypeID,
		arg.ShipName,
		arg.FetchedAt,
	)
	var i PresenceShip
	err := row.Scan(
		&i.CharacterID,
		&i.ShipItemID,
		&i.ShipTypeID,
		&i.ShipName,
		&i.FetchedAt,
	)
	return i, err
}
