// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package presence

import (
	"context"
)

const get = `-- name: Get :one
SELECT character_id, online, last_login, last_logout, logins, solar_system_id, station_id, structure_id, ship_type_id, ship_item_id, ship_name, online_at, location_at, ship_at FROM presence WHERE character_id = ?
`

func (q *Queries) Get(ctx context.Context, characterID int64) (Presence, error) {
	row := q.db.QueryRowContext(ctx, get, characterID)
	var i Presence
	err := row.Scan(
		&i.CharacterID,
		&i.Online,
		&i.LastLogin,
		&i.LastLogout,
		&i.Logins,
		&i.SolarSystemID,
		&i.StationID,
		&i.StructureID,
		&i.ShipTypeID,
		&i.ShipItemID,
		&i.ShipName,
		&i.OnlineAt,
		&i.LocationAt,
		&i.ShipAt,
	)
	return i, err
}

const list = `-- name: List :many
SELECT character_id, online, last_login, last_logout, logins, solar_system_id, station_id, structure_id, ship_type_id, ship_item_id, ship_name, online_at, location_at, ship_at FROM presence ORDER BY character_id
`

func (q *Queries) List(ctx context.Context) ([]Presence, error) {
	rows, err := q.db.QueryContext(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Presence
	for rows.Next() {
		var i Presence
		if err := rows.Scan(
			&i.CharacterID,
			&i.Online,
			&i.LastLogin,
			&i.LastLogout,
			&i.Logins,
			&i.SolarSystemID,
			&i.StationID,
			&i.StructureID,
			&i.ShipTypeID,
			&i.ShipItemID,
			&i.ShipName,
			&i.OnlineAt,
			&i.LocationAt,
			&i.ShipAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO presence (character_id, solar_system_id, station_id, structure_id, location_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    solar_system_id = excluded.solar_system_id,
    station_id = excluded.station_id,
    structure_id = excluded.structure_id,
    location_at = excluded.location_at
`

type UpsertLocationParams struct {
	CharacterID   int64  `json:"characterId"`
	SolarSystemID *int64 `json:"solarSystemId"`
	StationID     *int64 `json:"stationId"`
	StructureID   *int64 `json:"structureId"`
	LocationAt    *int64 `json:"locationAt"`
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocation,
		arg.CharacterID,
		arg.SolarSystemID,
		arg.StationID,
		arg.StructureID,
		arg.LocationAt,
	)
	return err
}

const upsertOnline = `-- name: UpsertOnline :exec
INSERT INTO presence (character_id, online, last_login, last_logout, logins, online_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    online = excluded.online,
    last_login = excluded.last_login,
    last_logout = excluded.last_logout,
    logins = excluded.logins,
    online_at = excluded.online_at
`

type UpsertOnlineParams struct {
	CharacterID int64  `json:"characterId"`
	Online      int64  `json:"online"`
	LastLogin   *int64 `json:"lastLogin"`
	LastLogout  *int64 `json:"lastLogout"`
	Logins      *int64 `json:"logins"`
	OnlineAt    *int64 `json:"onlineAt"`
}

func (q *Queries) UpsertOnline(ctx context.Context, arg UpsertOnlineParams) error {
	_, err := q.db.ExecContext(ctx, upsertOnline,
		arg.CharacterID,
		arg.Online,
		arg.LastLogin,
		arg.LastLogout,
		arg.Logins,
		arg.OnlineAt,
	)
	return err
}

const upsertShip = `-- name: UpsertShip :exec
INSERT INTO presence (character_id, ship_type_id, ship_item_id, ship_name, ship_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    ship_type_id = excluded.ship_type_id,
    ship_item_id = excluded.ship_item_id,
    ship_name = excluded.ship_name,
    ship_at = excluded.ship_at
`

type UpsertShipParams struct {
	CharacterID int64   `json:"characterId"`
	ShipTypeID  *int64  `json:"shipTypeId"`
	ShipItemID  *int64  `json:"shipItemId"`
	ShipName    *string `json:"shipName"`
	ShipAt      *int64  `json:"shipAt"`
}

func (q *Queries) UpsertShip(ctx context.Context, arg UpsertShipParams) error {
	_, err := q.db.ExecContext(ctx, upsertShip,
		arg.CharacterID,
		arg.ShipTypeID,
		arg.ShipItemID,
		arg.ShipName,
		arg.ShipAt,
	)
	return err
}
