// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package presence

type Presence struct {
	CharacterID   int64   `json:"characterId"`
	Online        int64   `json:"online"`
	LastLogin     *int64  `json:"lastLogin"`
	LastLogout    *int64  `json:"lastLogout"`
	Logins        *int64  `json:"logins"`
	SolarSystemID *int64  `json:"solarSystemId"`
	StationID     *int64  `json:"stationId"`
	StructureID   *int64  `json:"structureId"`
	ShipTypeID    *int64  `json:"shipTypeId"`
	ShipItemID    *int64  `json:"shipItemId"`
	ShipName      *string `json:"shipName"`
	OnlineAt      *int64  `json:"onlineAt"`
	LocationAt    *int64  `json:"locationAt"`
	ShipAt        *int64  `json:"shipAt"`
}
