// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package presence

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
	"github.com/eve-online-tools/lib-esi-go/common/station"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type PresenceLocation struct {
	CharacterID   int64                  `json:"characterId"`
	SolarSystemID solarsystem.Identifier `json:"solarSystemId"`
	StationID     *station.Identifier    `json:"stationId"`
	StructureID   *item.Identifier       `json:"structureId"`
	FetchedAt     time.Time              `json:"fetchedAt"`
}

type PresenceOnline struct {
	CharacterID int64      `json:"characterId"`
	Online      bool       `json:"online"`
	LastLogin   *time.Time `json:"lastLogin"`
	LastLogout  *time.Time `json:"lastLogout"`
	Logins      *int64     `json:"logins"`
	FetchedAt   time.Time  `json:"fetchedAt"`
}

type PresenceShip struct {
	CharacterID int64             `json:"characterId"`
	ShipItemID  item.Identifier   `json:"shipItemId"`
	ShipTypeID  typeid.Identifier `json:"shipTypeId"`
	ShipName    string            `json:"shipName"`
	FetchedAt   time.Time         `json:"fetchedAt"`
}
